-- 001_init.sql — NFC TimeSheets canonical schema (iteration 3A).
-- decision-2: Postgres replaces the JSON file store.
-- decision-16: Postgres 16 local to the exe.dev VM, unix socket / 127.0.0.1 only.
--
-- ponytail: no migration framework. Plain numbered .sql files applied by db/migrate.js
--   (a ~15-line runner over `psql`). Ceiling: no down-migrations, no checksum
--   verification, no branching/merge story. Upgrade path if we ever outgrow it:
--   node-pg-migrate — it also drives plain SQL files, so these files carry over.
--
-- CONSTRAINT ON THIS FILE AND EVERY FUTURE MIGRATION:
--   Do NOT write BEGIN/COMMIT here. migrate.js runs each file with `psql -1`,
--   i.e. the whole file plus its schema_migrations bookkeeping row is already one
--   transaction. An explicit BEGIN would break that.
--
-- This file was rewritten in place (decision-19/20/21). Legitimate only because
-- NOTHING has shipped and no database holds data yet. Once production exists, the
-- rule in db/README.md applies without exception: never edit an applied migration.

-- ---------------------------------------------------------------------------
-- workers
-- ---------------------------------------------------------------------------
CREATE TABLE workers (
  id                BIGSERIAL PRIMARY KEY,
  name              TEXT NOT NULL,
  hourly_rate_cents INTEGER NOT NULL DEFAULT 0,
  active            BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- admins — web-admin password auth (decision-20).
-- Replaces the X-Admin-Pin header, which had no rate limit and no length floor
-- and became untenable once the exe.dev proxy went public (AASA must be fetchable).
-- password_hash is a full PHC string (algorithm + params + salt + hash), so the
-- KDF can be rotated without a schema change. Never store a plaintext or a PIN.
-- ---------------------------------------------------------------------------
CREATE TABLE admins (
  id            BIGSERIAL PRIMARY KEY,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Server-side sessions, not stateless JWTs: 5-20 users, one server, and logout
-- must actually revoke. `token` is a high-entropy random string generated by the
-- API (node:crypto), which is why it can be the primary key.
CREATE TABLE sessions (
  token      TEXT PRIMARY KEY,
  admin_id   BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Cheap sweep of expired sessions: DELETE FROM sessions WHERE expires_at < now().
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- ---------------------------------------------------------------------------
-- locations
-- decision-21: the NDEF URI carries the UUID, never the slug:
--   https://timesheets.exe.xyz/t?l=<id>
-- `id` is a random UUID precisely so a tag identifier is not guessable. `slug` is
-- human-readable and exists ONLY for the admin UI and log lines. A slug must never
-- appear in a tag URI.
-- decision-5: location identity lives in the URI, not the tag hardware UID.
-- decision-15: tags are left UNLOCKED, so the value off the tag is still untrusted
--   input. The API must ALWAYS resolve it server-side and reject unknown/inactive
--   locations. Unguessable is not the same as authenticated.
-- gen_random_uuid() is built into Postgres 13+; no pgcrypto extension needed.
-- ---------------------------------------------------------------------------
CREATE TABLE locations (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug       TEXT UNIQUE NOT NULL,
  name       TEXT NOT NULL,
  address    TEXT,
  lat        DOUBLE PRECISION,
  lng        DOUBLE PRECISION,
  active     BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- shifts
--
-- decision-19: the iOS app posts the shift at clock-IN with end_time NULL, then
-- closes it at clock-out. The server is authoritative for open shifts, so every
-- open shift is visible to the 8h timer while it is still running.
--
-- decision-10 flag semantics — TWO independent facts, never one column:
--   auto_closed  = the 8h timer closed this shift. No human was involved.
--   corrected_at = a human (the worker) resolved it. NULL means unresolved.
-- The old single `manual_finish` column was set by BOTH the timer and by worker
-- resolution and therefore could not distinguish them. It is gone.
--   unresolved  <=>  auto_closed AND corrected_at IS NULL
-- That is the exact predicate GET /shifts/unresolved uses; no third flag exists to
-- drift out of sync with it (the old `needs_correction` was that third flag).
-- ---------------------------------------------------------------------------
CREATE TABLE shifts (
  id           BIGSERIAL PRIMARY KEY,
  worker_id    BIGINT NOT NULL REFERENCES workers(id),
  location_id  UUID   NOT NULL REFERENCES locations(id),
  start_time   TIMESTAMPTZ NOT NULL,
  end_time     TIMESTAMPTZ,                      -- NULL = still open
  auto_closed  BOOLEAN NOT NULL DEFAULT false,   -- closed by the 8h timer, not by a tap
  corrected_at TIMESTAMPTZ,                      -- when a human resolved it
  client_uuid  TEXT UNIQUE,                      -- idempotency key from the iOS app
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- client_uuid UNIQUE is what makes BOTH POST /shifts/open and POST /shifts/close
-- idempotent under retry (iOS resends on flaky network): open uses
-- ON CONFLICT (client_uuid) DO NOTHING, close matches the row by client_uuid.
-- The UNIQUE constraint above creates its own index.

-- FK lookups + the two admin aggregations (hours per worker, hours per location).
CREATE INDEX shifts_worker_id_idx   ON shifts (worker_id);
CREATE INDEX shifts_location_id_idx ON shifts (location_id);

-- Open shifts. Three consumers, all of them scan exactly this set:
--   1. the 8h auto-close systemd timer (decision-10, decision-16)
--        WHERE end_time IS NULL AND start_time < now() - interval '8 hours'
--   2. GET /shifts/unresolved
--   3. "is this worker already clocked in?" on tap
-- Under decision-19 this set is finally non-empty in practice — before it, the app
-- only ever posted already-completed shifts, so the whole chain was dead machinery.
-- Judgement call: the predicate is `end_time IS NULL`, so end_time itself is a
-- constant inside the index and useless as a key column. Keyed on start_time
-- instead, which is what all three queries actually range-scan / order by.
-- Stays tiny — only currently-open shifts are in it.
CREATE INDEX shifts_open_idx ON shifts (start_time) WHERE end_time IS NULL;

-- Overlap guard. At most ONE open shift per worker at any time, enforced by the
-- database rather than by a read-then-write in the API (which races two taps).
-- A double-punch at the door therefore cannot create two concurrent open shifts:
-- the second INSERT raises unique_violation (SQLSTATE 23505) and the API turns
-- that into "already clocked in". Partial, so it says nothing about closed shifts —
-- a worker can have any number of completed shifts, including several per day.
CREATE UNIQUE INDEX shifts_one_open_per_worker_idx ON shifts (worker_id) WHERE end_time IS NULL;

-- Admin list view + payroll period filters: newest shifts first.
CREATE INDEX shifts_start_time_idx ON shifts (start_time DESC);

-- 3B (owners, annual contracts, materials, P&L) is NOT built here. It attaches to
-- locations.id and shifts.id; nothing in this file needs to change for it.
