'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useFormatter, useTranslations } from 'next-intl'
import { type FormEvent, useCallback, useEffect, useId, useMemo, useRef, useState } from 'react'
import { ConfirmModal } from '@/components/ConfirmModal'
import { Drawer } from '@/components/Drawer'
import { EmptyState } from '@/components/EmptyState'
import { Field } from '@/components/Field'
import { FilterChips } from '@/components/FilterChips'
import { ListPanel } from '@/components/ListPanel'
import { PageHeader } from '@/components/PageHeader'
import {
  ApiError,
  type BuildingsSnapshot,
  type Contact,
  createClientLink,
  deactivateLocation,
  fetchBuildingsSnapshot,
  type Location,
  revokeClientLink,
  type Shift,
  saveClient,
  saveContact,
  saveLocation,
} from '@/lib/api'
import { filterHref, useFilters } from '@/lib/filters'
import type { ErrorKey } from '@/lib/locale'
import { centsToPlainEuros, parseEuroToCents } from '@/lib/money'
import { LOGIN_PATH } from '@/lib/nav'
import { businessMidnight, type PeriodRange, withinRange } from '@/lib/period'
import { clientPortalUrl } from '@/lib/portal'
import {
  BUSINESS_TIME_ZONE,
  blocksPayroll,
  durationMinutes,
  formatDuration,
  shiftState,
  toBusinessInput,
} from '@/lib/shifts'
import { tagUri } from '@/lib/tag'

/**
 * Buildings screen — where a building is, who pays for it, what we charge, how much time we
 * agreed to and how much we have actually spent this month, the string that goes on its NFC
 * tag, and the link its client can be given.
 *
 * The tag URI is the load-bearing part. A tag carries `https://…/t?l=<location uuid>`
 * (decision-21): the UUID is the identity, generated by the database, and the slug is only a
 * human label. A wrong string on a sticker is discovered when a worker taps it and nothing
 * happens, and fixing it costs a site visit — so the full URI stays ON THE ROW, verbatim,
 * never elided and never one click away behind an overlay.
 *
 * The client and the point of contact can both be CREATED FROM THE SAME DRAWER. Sending the
 * director to two other screens before they can file one building is the friction that makes
 * a non-technical user stop using the panel; /clients/ exists for tidying up afterwards and
 * is never a prerequisite. It is a disclosure INSIDE this drawer and deliberately NOT a
 * second drawer on top of the first (owner, explicitly): a focus trap inside a focus trap is
 * a bug farm.
 *
 * Deactivation is soft, always: shifts reference buildings and the history has to survive.
 * One client component with `useState` + `fetch`, because this bundle is a static export
 * (decision-16) and no server component may fetch this data.
 */

/** Mirrors v.slug() in server/lib/validate.js. The server decides for real. */
const SLUG_RE = /^[a-z0-9][a-z0-9_-]*$/
/** Shape check only, mirroring v.optionalEmail(). */
const EMAIL_RE = /^[^\s@,]+@[^\s@,.]+(\.[^\s@,.]+)+$/
/** Mirrors v.optionalPhone(): digits and separators, no letters. */
const PHONE_RE = /^[0-9+()/.\s-]+$/
/**
 * Whole hours only.
 *
 * ponytail: the column stores minutes, and the form offers hours without a fraction. Every
 * target the director quoted is a round number of hours a month, and integer hours convert
 * to minutes exactly — no float multiplication anywhere near a number that later gets
 * subtracted from recorded time. Upgrade path when a 37.5 h contract appears: accept one
 * decimal place and convert tenths to 6-minute steps, still integer-only.
 */
const HOURS_RE = /^\d{1,4}$/
/** v.optionalMinutes() ceiling, 446 400 minutes, expressed in hours. */
const MAX_TARGET_HOURS = 7440

/** '' = none, 'new' = create it inline, anything else = that row's id. */
const NEW_ROW = 'new'
const NONE = ''

type Draft = {
  /** Absent = create. Present = update that row (a UUID). */
  id?: string
  name: string
  slug: string
  address: string
  active: boolean
  /** Carried through an edit untouched: the update writes every column (see LocationInput). */
  lat: number | null
  lng: number | null
  clientChoice: string
  newClientName: string
  contactChoice: string
  newContactName: string
  newContactEmail: string
  newContactPhone: string
  /** Euros as typed. Converted to integer cents at submit, never held as a float. */
  monthly: string
  /** Whole hours as typed. Converted to integer minutes at submit. */
  targetHours: string
}

const EMPTY_DRAFT: Draft = {
  name: '',
  slug: '',
  address: '',
  active: true,
  lat: null,
  lng: null,
  clientChoice: NONE,
  newClientName: '',
  contactChoice: NONE,
  newContactName: '',
  newContactEmail: '',
  newContactPhone: '',
  monthly: '',
  targetHours: '',
}

function draftOf(location: Location): Draft {
  return {
    ...EMPTY_DRAFT,
    id: location.id,
    name: location.name,
    slug: location.slug,
    address: location.address ?? '',
    active: location.active,
    lat: location.lat,
    lng: location.lng,
    clientChoice: location.client_id === null ? NONE : String(location.client_id),
    contactChoice: location.contact_id === null ? NONE : String(location.contact_id),
    monthly:
      location.monthly_contract_cents === null
        ? ''
        : centsToPlainEuros(location.monthly_contract_cents),
    // Only whole hours can be typed here, so a stored value that is not a whole hour cannot
    // be shown in this field without changing it. It is left empty and the exact stored
    // value is named in a hint next to the field instead of being silently rounded.
    targetHours:
      location.target_minutes_per_month !== null && location.target_minutes_per_month % 60 === 0
        ? String(location.target_minutes_per_month / 60)
        : '',
  }
}

/** Message keys inside the `locations` namespace, so field errors stay translatable. */
type ErrorMessage =
  | 'errorNameRequired'
  | 'errorSlugRequired'
  | 'errorSlugShape'
  | 'errorSlugTaken'
  | 'errorClientNameRequired'
  | 'errorContactNameRequired'
  | 'errorContactNeedsClient'
  | 'errorContactEmailShape'
  | 'errorContactPhoneShape'
  | 'errorMonthlyInvalid'
  | 'errorTargetInvalid'
  | 'errorRejected'

type FieldErrors = {
  name?: ErrorMessage
  slug?: ErrorMessage
  newClientName?: ErrorMessage
  contact?: ErrorMessage
  newContactName?: ErrorMessage
  newContactEmail?: ErrorMessage
  newContactPhone?: ErrorMessage
  monthly?: ErrorMessage
  targetHours?: ErrorMessage
}

/**
 * Which drawer step a field lives on. A validation failure has to be VISIBLE, so a submit
 * that fails on a step-1 field sends the drawer back to step 1 rather than reporting an
 * error about a control nobody can see.
 */
const STEP_ONE_FIELDS = [
  'name',
  'slug',
  'newClientName',
  'contact',
  'newContactName',
  'newContactEmail',
  'newContactPhone',
] as const

function hasStepOneError(errors: FieldErrors): boolean {
  return STEP_ONE_FIELDS.some((key) => errors[key] !== undefined)
}

/** Recorded and not-yet-counted time for one building in the CHOSEN calendar month. */
type MonthTime = { minutes: number; pending: number }

/** `YYYY-MM`, exactly what `<input type="month">` produces and consumes. */
const MONTH_RE = /^\d{4}-(0[1-9]|1[0-2])$/

/** The Vienna calendar month an instant falls in. */
function businessMonthOf(iso: string): string {
  return toBusinessInput(iso).slice(0, 7)
}

/**
 * `YYYY-MM` -> the half-open `[from, to)` of that month in VIENNA wall time.
 *
 * Not the browser's zone: 1 August 00:00 in Vienna is 31 July 22:00 UTC, and a shift in
 * that gap belongs to July on every other screen. `businessMidnight` handles month 13.
 */
function monthRange(month: string): PeriodRange {
  const year = Number(month.slice(0, 4))
  const index = Number(month.slice(5, 7))
  return { from: businessMidnight(year, index, 1), to: businessMidnight(year, index + 1, 1) }
}

/**
 * Time per building in `range`.
 *
 * A shift that is still open, or that the 8-hour timer closed and nobody has confirmed, is
 * counted as PENDING and not as time worked (decision-10): a start-plus-8h stub is a
 * placeholder, and adding it to the hours would answer "are we overservicing" with a guess.
 */
function timeInMonth(shifts: readonly Shift[], range: PeriodRange): Map<string, MonthTime> {
  const byLocation = new Map<string, MonthTime>()
  for (const shift of shifts) {
    if (!withinRange(shift.start_time, range)) continue
    const entry = byLocation.get(shift.location_id) ?? { minutes: 0, pending: 0 }
    if (shift.end_time === null || blocksPayroll(shiftState(shift))) entry.pending += 1
    else entry.minutes += durationMinutes(shift.start_time, shift.end_time)
    byLocation.set(shift.location_id, entry)
  }
  return byLocation
}

export default function LocationsPage() {
  const t = useTranslations('locations')
  const tFilter = useTranslations('filters')
  const tError = useTranslations('error')
  const format = useFormatter()
  const router = useRouter()

  const formId = useId()
  const nameId = useId()
  const slugId = useId()
  const addressId = useId()
  const clientId = useId()
  const newClientId = useId()
  const contactId = useId()
  const newContactId = useId()
  const newContactEmailId = useId()
  const newContactPhoneId = useId()
  const monthlyId = useId()
  const targetId = useId()
  const monthId = useId()
  const monthHintId = useId()
  const activeId = useId()

  // null = still loading. Empty lists = loaded and genuinely empty, the first-run state.
  const [snapshot, setSnapshot] = useState<BuildingsSnapshot | null>(null)
  const [loadError, setLoadError] = useState<ErrorKey | null>(null)
  /** null = the drawer is closed. There is no half-open form on this screen any more. */
  const [draft, setDraft] = useState<Draft | null>(null)
  /** 1 = the building and its client. 2 = the contract and the agreed time. */
  const [step, setStep] = useState<1 | 2>(1)
  /** Step 2's fields, so focus can be moved into them when the step changes. */
  const stepTwoRef = useRef<HTMLDivElement | null>(null)
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({})
  const [formError, setFormError] = useState<ErrorMessage | null>(null)
  /** A 5xx or an offline browser during a SAVE. Shown in the drawer, which stays open. */
  const [saveError, setSaveError] = useState<ErrorKey | null>(null)
  const [busy, setBusy] = useState(false)
  /** The building waiting for a plain yes/no before it is stood down. */
  const [pendingDeactivate, setPendingDeactivate] = useState<Location | null>(null)
  /** The link just minted, shown once. Never re-readable — see `createClientLink`. */
  const [freshLink, setFreshLink] = useState<{
    url: string
    building: string
    contact: string
  } | null>(null)
  /** Result of the last copy / share action, announced in a permanent live region. */
  const [notice, setNotice] = useState<{ ok: boolean; text: string } | null>(null)

  /** A dead session must not render an empty table that looks like "no buildings yet". */
  const handleAuthLoss = useCallback(
    (cause: unknown): boolean => {
      if (cause instanceof ApiError && (cause.status === 401 || cause.status === 403)) {
        router.replace(LOGIN_PATH)
        return true
      }
      return false
    },
    [router],
  )

  const load = useCallback(
    async (signal?: AbortSignal) => {
      try {
        setSnapshot(await fetchBuildingsSnapshot(signal))
        setLoadError(null)
      } catch (cause) {
        if (cause instanceof DOMException && cause.name === 'AbortError') return
        if (handleAuthLoss(cause)) return
        setLoadError(cause instanceof ApiError ? cause.messageKey : 'server')
      }
    },
    [handleAuthLoss],
  )

  useEffect(() => {
    const controller = new AbortController()
    void load(controller.signal)
    return () => controller.abort()
  }, [load])

  /**
   * Focus follows the step. The button that advanced the drawer is REPLACED when step 2
   * renders (different key, see the footer), so without this the browser drops focus on
   * <body> and a keyboard user is standing outside a dialog that is still open.
   *
   * The step-2 CONTAINER takes focus, not its first field: a text input is a submit
   * surface (implicit submission), so a second Enter half a second after the first would
   * have created the object straight through step 2 without it ever being read — the same
   * outcome C1 produced, reached a different way. Measured by demo/audit-keyboard.mjs
   * ("a SECOND Enter after Weiter does not silently save the object").
   *
   * Depends on `step` alone on purpose: adding `draft` would re-steal focus on every
   * keystroke, because every keystroke replaces the draft.
   */
  useEffect(() => {
    if (step !== 2) return
    stepTwoRef.current?.focus()
  }, [step])

  /**
   * The month the time column reports on. It used to be hard-locked to the current calendar
   * month with no control at all, so on the 3rd of a month every building read 0:00 and —
   * where a Sollzeit was agreed — the screen asserted "40:00 unter der Sollzeit", which is a
   * false statement about a contract and not a display quirk.
   */
  const [month, setMonth] = useState(() => businessMonthOf(new Date().toISOString()))
  const monthValid = MONTH_RE.test(month)
  const monthTime = useMemo(
    () =>
      monthValid
        ? timeInMonth(snapshot?.shifts ?? [], monthRange(month))
        : new Map<string, MonthTime>(),
    [snapshot, month, monthValid],
  )

  /**
   * When the chosen month is empty, the ledger's real extent is what tells "nobody cleaned
   * in July" apart from "the records are gone". It comes from the server unbounded by both
   * the period and the row cap.
   */
  const latestStart = snapshot?.shift_bounds.latest ?? null
  const latestMonth = latestStart === null ? null : businessMonthOf(latestStart)
  const monthIsEmpty = monthValid && monthTime.size === 0

  const allLocations = snapshot?.locations ?? []
  const clients = snapshot?.clients ?? []
  const contacts = snapshot?.contacts ?? []
  const grants = snapshot?.portal_grants ?? []

  /**
   * THE FILTER CONTRACT (decision-38). Three parameters land here:
   *
   *   `?state=noTag`  the dashboard's „Tag-URLs prüfen" row — the buildings with no shift
   *                   on record, which usually means no working tag on the wall
   *   `?client=<id>`  a company's buildings, from `/clients/`
   *   `?open=<uuid>`  open the edit drawer on that building, from the Objektpanel
   *
   * `noTag` is computed the same way the dashboard computes it — no shift in the loaded
   * payload — and the payload is capped, so the truncation note below applies to it too.
   */
  const [filters, setFilters] = useFilters()
  const seenLocationIds = new Set((snapshot?.shifts ?? []).map((shift) => shift.location_id))
  const noTagOnly = filters.state === 'noTag'
  const locations = allLocations.filter((location) => {
    if (noTagOnly && !(location.active && !seenLocationIds.has(location.id))) return false
    if (filters.client !== null && location.client_id !== filters.client) return false
    return true
  })

  const filterClientName =
    filters.client === null
      ? null
      : (clients.find((client) => client.id === filters.client)?.name ?? null)
  const clientUnknown = filters.client !== null && snapshot !== null && filterClientName === null

  /** Contacts of the chosen company only: a contact belongs to exactly one company. */
  const contactsForClient: Contact[] =
    draft === null || draft.clientChoice === NONE || draft.clientChoice === NEW_ROW
      ? []
      : contacts.filter((contact) => String(contact.client_id) === draft.clientChoice)

  function openCreate() {
    setDraft(EMPTY_DRAFT)
    setStep(1)
    setFieldErrors({})
    setFormError(null)
    setSaveError(null)
    setNotice(null)
  }

  function openEdit(location: Location) {
    setDraft(draftOf(location))
    setStep(1)
    setFieldErrors({})
    setFormError(null)
    setSaveError(null)
    setNotice(null)
  }

  /** Escape, the scrim and Cancel all land here. Focus restoration is the Drawer's job. */
  function closeDrawer() {
    setDraft(null)
    setFieldErrors({})
    setFormError(null)
    setSaveError(null)
    // `?open=` is what put the drawer here; leaving it in the URL would reopen the drawer
    // on the next render and make the close button do nothing. 'replace', so leaving the
    // screen still takes one back press.
    if (filters.open !== null) setFilters({ open: null }, 'replace')
  }

  /**
   * `?open=<uuid>` — the Objektpanel's „Objekt bearbeiten · Tag-URL" link, which is how the
   * director reaches the one control on this screen a wrong sticker costs a site visit for.
   * Runs once per id: reopening on every render would make the drawer impossible to close.
   */
  const [openedFor, setOpenedFor] = useState<string | null>(null)
  useEffect(() => {
    if (snapshot === null || filters.open === null || filters.open === openedFor) return
    setOpenedFor(filters.open)
    const wanted = snapshot.locations.find((location) => location.id === filters.open)
    if (wanted !== undefined) {
      setDraft(draftOf(wanted))
      setStep(1)
      setFieldErrors({})
      setFormError(null)
      setSaveError(null)
    }
  }, [snapshot, filters.open, openedFor])

  /** A well-formed building id in `?open=` that no row matches. Said, never swallowed. */
  const openUnknown =
    snapshot !== null &&
    filters.open !== null &&
    !snapshot.locations.some((location) => location.id === filters.open)

  /** Changing the company invalidates the contact choice — a stale one belongs elsewhere. */
  function chooseClient(value: string) {
    if (draft === null) return
    setDraft({ ...draft, clientChoice: value, contactChoice: NONE })
  }

  /** Maps a failed save onto the field it belongs to. 409 can only be the slug. */
  function reportSaveFailure(cause: unknown) {
    if (handleAuthLoss(cause)) return
    if (cause instanceof ApiError && cause.status === 409) {
      setFieldErrors({ slug: 'errorSlugTaken' })
      setFormError('errorSlugTaken')
      // The slug lives on step 1. An error about a field the drawer is not showing is an
      // error nobody can act on.
      setStep(1)
      return
    }
    setFormError(
      cause instanceof ApiError && cause.status >= 400 && cause.status < 500
        ? 'errorRejected'
        : null,
    )
    if (cause instanceof ApiError && (cause.status === 0 || cause.status >= 500)) {
      setFieldErrors({})
      setLoadError(cause.messageKey)
      setSaveError(cause.messageKey)
    }
  }

  /** Client-side validation is UX only — server/lib/validate.js decides for real. */
  function validate(current: Draft): FieldErrors {
    const errors: FieldErrors = {}
    const name = current.name.trim()
    const slug = current.slug.trim().toLowerCase()
    const targetHours = current.targetHours.trim()

    if (name === '') errors.name = 'errorNameRequired'
    if (slug === '') errors.slug = 'errorSlugRequired'
    else if (slug.length > 64 || !SLUG_RE.test(slug)) errors.slug = 'errorSlugShape'
    if (current.clientChoice === NEW_ROW && current.newClientName.trim() === '') {
      errors.newClientName = 'errorClientNameRequired'
    }
    if (current.contactChoice === NEW_ROW) {
      if (current.clientChoice === NONE) errors.contact = 'errorContactNeedsClient'
      if (current.newContactName.trim() === '') errors.newContactName = 'errorContactNameRequired'
      if (current.newContactEmail.trim() !== '' && !EMAIL_RE.test(current.newContactEmail.trim())) {
        errors.newContactEmail = 'errorContactEmailShape'
      }
      if (current.newContactPhone.trim() !== '' && !PHONE_RE.test(current.newContactPhone.trim())) {
        errors.newContactPhone = 'errorContactPhoneShape'
      }
    }
    if (current.monthly.trim() !== '' && parseEuroToCents(current.monthly) === null) {
      errors.monthly = 'errorMonthlyInvalid'
    }
    if (
      targetHours !== '' &&
      (!HOURS_RE.test(targetHours) || Number.parseInt(targetHours, 10) > MAX_TARGET_HOURS)
    ) {
      errors.targetHours = 'errorTargetInvalid'
    }
    return errors
  }

  /** Step 1 → step 2. Only step-1 errors block it; the contract fields are not filled yet. */
  function goToContract() {
    if (draft === null) return
    const errors = validate(draft)
    const stepOne = Object.fromEntries(
      STEP_ONE_FIELDS.filter((key) => errors[key] !== undefined).map((key) => [key, errors[key]]),
    ) as FieldErrors
    setFieldErrors(stepOne)
    setFormError(null)
    if (!hasStepOneError(stepOne)) setStep(2)
  }

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (busy || draft === null) return

    const errors = validate(draft)
    setFieldErrors(errors)
    setFormError(null)
    setSaveError(null)
    if (Object.keys(errors).length > 0) {
      if (hasStepOneError(errors)) setStep(1)
      return
    }

    const name = draft.name.trim()
    const slug = draft.slug.trim().toLowerCase()
    const address = draft.address.trim()
    const newClientName = draft.newClientName.trim()
    const newContactName = draft.newContactName.trim()
    const newContactEmail = draft.newContactEmail.trim()
    const newContactPhone = draft.newContactPhone.trim()
    const monthlyCents = draft.monthly.trim() === '' ? null : parseEuroToCents(draft.monthly)
    const targetHours = draft.targetHours.trim()

    setBusy(true)
    try {
      // A company and a person can be filed on the way to saving the building. Written
      // first, because the building has to reference their ids. If the building save then
      // fails (a taken slug), the company and the person still exist and the form is
      // pointed at them, so pressing Save again cannot create a second copy.
      let clientRef = draft.clientChoice === NONE ? null : Number(draft.clientChoice)
      if (draft.clientChoice === NEW_ROW) {
        const created = await saveClient({ name: newClientName, active: true })
        clientRef = created.id
        setDraft((current) =>
          current === null
            ? current
            : { ...current, clientChoice: String(created.id), newClientName: '' },
        )
      }

      let contactRef = draft.contactChoice === NONE ? null : Number(draft.contactChoice)
      if (draft.contactChoice === NEW_ROW && clientRef !== null) {
        const created = await saveContact({
          client_id: clientRef,
          name: newContactName,
          email: newContactEmail,
          phone: newContactPhone,
          active: true,
        })
        contactRef = created.id
        setDraft((current) =>
          current === null
            ? current
            : {
                ...current,
                contactChoice: String(created.id),
                newContactName: '',
                newContactEmail: '',
                newContactPhone: '',
              },
        )
      }

      await saveLocation({
        ...(draft.id === undefined ? {} : { id: draft.id }),
        name,
        slug,
        address,
        lat: draft.lat,
        lng: draft.lng,
        active: draft.active,
        client_id: clientRef,
        contact_id: contactRef,
        monthly_contract_cents: monthlyCents,
        target_minutes_per_month: targetHours === '' ? null : Number.parseInt(targetHours, 10) * 60,
      })
      // The result is announced by the PAGE: the drawer closes on success and would take
      // its own success message with it, unread.
      setNotice({ ok: true, text: t('saved') })
      closeDrawer()
      await load()
    } catch (cause) {
      // A FAILED save keeps the drawer open, so its message stays inside the drawer, next
      // to the fields it is about.
      reportSaveFailure(cause)
      // A company or a person created above is already in the database; reload so the
      // selects offer them instead of tempting a second attempt at "+ New".
      await load()
    } finally {
      setBusy(false)
    }
  }

  /**
   * Soft deactivate / reactivate. The tag on the wall stays physically valid, it just stops
   * resolving — nothing is ever destroyed, because shifts point at these rows.
   *
   * The two directions are NOT the same call. Deactivating goes through `DELETE`, which
   * also revokes the building's live client links: standing a building down while its
   * client's point of contact keeps reading its cleaning history is an access decision
   * about an outsider, and it must not depend on the admin remembering the Kundenlink
   * column. It touches only `active`, so no contract field can be cleared by the click.
   * That side effect is now SAID OUT LOUD in the confirmation, not left in a code comment.
   *
   * Reactivating is a normal save, and every column is written back: the route's UPDATE
   * sets them all, so an omitted contract field would be cleared by the click.
   */
  async function toggleActive(location: Location) {
    if (busy) return
    setBusy(true)
    setFormError(null)
    try {
      if (location.active) {
        await deactivateLocation(location.id)
      } else {
        await saveLocation({
          id: location.id,
          name: location.name,
          slug: location.slug,
          address: location.address ?? '',
          lat: location.lat,
          lng: location.lng,
          active: true,
          client_id: location.client_id,
          contact_id: location.contact_id,
          monthly_contract_cents: location.monthly_contract_cents,
          target_minutes_per_month: location.target_minutes_per_month,
        })
      }
      await load()
    } catch (cause) {
      reportSaveFailure(cause)
    } finally {
      setBusy(false)
    }
  }

  /**
   * Clipboard access fails on an insecure origin and can be refused by the browser. That is
   * not fatal here: the string is on screen in full, so the fallback is to say so and let
   * the admin select it by hand rather than leave them believing a copy happened.
   */
  async function copy(text: string, okText: string, failText: string) {
    try {
      await navigator.clipboard.writeText(text)
      setNotice({ ok: true, text: okText })
    } catch {
      setNotice({ ok: false, text: failText })
    }
  }

  /**
   * Mint the link for this building's contact. The URL is only complete once the browser's
   * own origin is prefixed: the server returns a path, because it has no configured public
   * origin and inventing one would be a deploy change.
   *
   * That path (`/portal/<token>`) is the JSON API route, NOT a page — `clientPortalUrl`
   * turns it into the page a client actually opens (`/reinigung/#k=<token>`, lib/portal.ts).
   * It answers null if the API ever changes that shape, and then no link is shown at all:
   * handing the director a URL that renders JSON is worse than telling them it failed.
   */
  async function shareBuilding(location: Location, contact: Contact) {
    if (busy) return
    setBusy(true)
    setNotice(null)
    setFreshLink(null)
    try {
      const path = await createClientLink(contact.id, location.id)
      const url = clientPortalUrl(window.location.origin, path)
      if (url === null) setNotice({ ok: false, text: t('shareFailed') })
      else setFreshLink({ url, building: location.name, contact: contact.name })
      await load()
    } catch (cause) {
      if (!handleAuthLoss(cause)) setNotice({ ok: false, text: t('shareFailed') })
    } finally {
      setBusy(false)
    }
  }

  async function stopSharing(tokenHash: string, location: Location) {
    if (busy) return
    setBusy(true)
    setFreshLink(null)
    try {
      await revokeClientLink(tokenHash)
      setNotice({ ok: true, text: t('shareStopped', { building: location.name }) })
      await load()
    } catch (cause) {
      if (!handleAuthLoss(cause)) setNotice({ ok: false, text: t('shareStopFailed') })
    } finally {
      setBusy(false)
    }
  }

  /**
   * "40:00 target. That is 3:20 over the target." — the whole answer to "are we
   * overservicing this building", in words, next to where the target was typed.
   */
  function targetSentence(minutes: number, target: number | null): string {
    if (target === null) return t('timeTargetNone')
    const stated = t('timeTarget', { target: formatDuration(target) })
    if (minutes > target) {
      return `${stated} ${t('timeOver', { delta: formatDuration(minutes - target) })}`
    }
    if (minutes < target) {
      return `${stated} ${t('timeUnder', { delta: formatDuration(target - minutes) })}`
    }
    return `${stated} ${t('timeExact')}`
  }

  /**
   * Why this building can or cannot be shared, and the control to do it. A grant needs an
   * active contact and an active building (the route enforces both), so the reason is
   * spelled out rather than leaving a disabled button with no explanation.
   */
  function shareCell(location: Location, contact: Contact | undefined) {
    const grant = grants.find((row) => row.location_id === location.id)
    const canShare = contact?.active === true && location.active

    if (grant !== undefined) {
      return (
        <>
          <span>
            {t('shareActive', {
              name: grant.contact_name,
              date: format.dateTime(new Date(grant.created_at), { dateStyle: 'medium' }),
            })}
          </span>
          <p className="form-actions">
            <button
              type="button"
              className="btn btn-quiet"
              onClick={() => stopSharing(grant.token_hash, location)}
            >
              {t('shareStop')}
              <span className="visually-hidden">{t('forLocation', { name: location.name })}</span>
            </button>
            {canShare ? (
              <button
                type="button"
                className="btn btn-quiet"
                onClick={() => shareBuilding(location, contact)}
              >
                {t('shareNew')}
                <span className="visually-hidden">{t('forLocation', { name: location.name })}</span>
              </button>
            ) : null}
          </p>
        </>
      )
    }

    if (contact === undefined) return <span className="cell-muted">{t('shareNoContact')}</span>
    if (!contact.active) {
      return <span className="cell-muted">{t('shareContactInactive', { name: contact.name })}</span>
    }
    if (!location.active) {
      return <span className="cell-muted">{t('shareInactiveBuilding')}</span>
    }
    return (
      <button
        type="button"
        className="btn btn-quiet"
        onClick={() => shareBuilding(location, contact)}
      >
        {t('shareButton', { name: contact.name })}
        <span className="visually-hidden">{t('forLocation', { name: location.name })}</span>
      </button>
    )
  }

  const editedLocation =
    draft?.id === undefined ? undefined : locations.find((row) => row.id === draft.id)
  /** Named rather than rounded into the hours field. See draftOf(). */
  const storedTargetNote =
    editedLocation?.target_minutes_per_month != null &&
    editedLocation.target_minutes_per_month % 60 !== 0
      ? t('targetStored', { value: formatDuration(editedLocation.target_minutes_per_month) })
      : ''
  const truncated = snapshot !== null && snapshot.shifts.length >= snapshot.shift_limit
  const drawerError =
    formError !== null ? t(formError) : saveError !== null ? tError(saveError) : ''

  return (
    <>
      <PageHeader
        title={t('heading')}
        question={t('question')}
        action={
          <button type="button" className="btn btn-primary" onClick={openCreate}>
            {t('createHeading')}
          </button>
        }
      />

      {/* Permanent live regions, on the PAGE and never inside an overlay: an overlay that
          closes on success takes its own success message with it, unread — and a failed
          copy announced into a drawer the user just closed is how the wrong string ends up
          pasted into a message to a worker. */}
      <p className="form-error" role="alert">
        {loadError === null ? '' : tError(loadError)}
      </p>
      <p className={notice?.ok === false ? 'form-error' : 'form-status'} role="status">
        {notice === null ? '' : notice.text}
      </p>

      {/* The filter, echoed and removable (decision-38 rule 3): a list of three buildings
          because a link narrowed it must not read as a company with three buildings. */}
      <FilterChips
        chips={[
          noTagOnly
            ? {
                key: 'state',
                label: tFilter('state'),
                value: tFilter('stateNoTag'),
                onRemove: () => setFilters({ state: null }, 'replace'),
              }
            : null,
          filters.client === null
            ? null
            : {
                key: 'client',
                label: tFilter('client'),
                value: filterClientName ?? tFilter('unknownClient'),
                unknown: clientUnknown,
                onRemove: () => setFilters({ client: null }, 'replace'),
              },
        ].filter((chip) => chip !== null)}
      />
      {clientUnknown || openUnknown ? (
        <p className="notice bad">{tFilter('unknownNotice')}</p>
      ) : null}

      {/* The tag rule, permanently: the URI goes on the sticker exactly as printed, the
          identity is the UUID, and the slug is never on the tag (decision-21). */}
      <p className="note">{t('tagExplainer')}</p>

      {/* The one and only sighting of the link. Not a dialog: the director has to be able
          to read it, copy it, and paste it into their mail client without the panel
          trapping focus or hiding the row it belongs to. */}
      <div role="status" aria-live="polite">
        {freshLink === null ? null : (
          <div className="note share-panel">
            <p>
              <strong>
                {t('shareReady', { name: freshLink.contact, building: freshLink.building })}
              </strong>
            </p>
            <code className="code-block">{freshLink.url}</code>
            <p className="form-actions">
              <button
                type="button"
                className="btn btn-primary"
                onClick={() => copy(freshLink.url, t('shareCopied'), t('shareCopyFailed'))}
              >
                {t('shareCopy')}
              </button>
            </p>
            <p>{t('shareExplain', { name: freshLink.contact })}</p>
            <p>{t('shareOnce')}</p>
          </div>
        )}
      </div>

      {/* The month the time column reports on. Native control: no dependency, keyboard
          reachable, and it already speaks the browser's locale. */}
      <div className="filter-bar">
        <div className="field">
          <label htmlFor={monthId}>{t('fieldMonth')}</label>
          <input
            id={monthId}
            type="month"
            value={month}
            aria-describedby={monthHintId}
            aria-invalid={!monthValid}
            onChange={(event) => setMonth(event.target.value)}
          />
          <p className="field-hint" id={monthHintId}>
            {t('monthHint')}
          </p>
        </div>
      </div>

      {/* Never let an empty month read as an empty database. Live region: changing the
          month above is what makes this appear and disappear. */}
      <div role="status">
        {snapshot === null || !monthIsEmpty ? null : (
          <div className="note">
            <p>{t('monthEmpty')}</p>
            {latestStart === null || latestMonth === null ? (
              <p>{t('monthNever')}</p>
            ) : (
              <>
                <p>
                  {t('monthLatest', {
                    date: format.dateTime(new Date(latestStart), {
                      dateStyle: 'long',
                      timeZone: BUSINESS_TIME_ZONE,
                    }),
                  })}
                </p>
                {latestMonth === month ? null : (
                  <p className="form-actions">
                    <button
                      type="button"
                      className="btn btn-ghost"
                      onClick={() => setMonth(latestMonth)}
                    >
                      {t('monthJump')}
                    </button>
                  </p>
                )}
              </>
            )}
          </div>
        )}
      </div>

      {snapshot !== null && truncated ? (
        <p className="note bad">{t('truncatedNote', { limit: snapshot.shift_limit })}</p>
      ) : null}

      <ListPanel
        title={t('listHeading')}
        padded={snapshot === null}
        action={
          <Link className="btn btn-quiet" href="/clients/">
            {t('clientsLink')}
          </Link>
        }
      >
        {snapshot === null ? (
          <p role="status">{t('loading')}</p>
        ) : locations.length === 0 ? (
          /* THREE different sentences, and they are not interchangeable. „Noch keine
             Objekte angelegt" said to a company with forty of them is the misreading this
             contract exists to stop — and so is „nur Objekte ohne erfasste Schicht" when
             what actually emptied the list was a client filter. The empty state names the
             filter that caused it, or says the portfolio is genuinely empty. */
          <EmptyState>
            {noTagOnly
              ? t('filterNoTag')
              : filters.client !== null
                ? t('filterClientEmpty')
                : t('emptyBodyNew')}
          </EmptyState>
        ) : (
          <table className="data-table" aria-busy={busy}>
            <caption className="visually-hidden">{t('tableCaption')}</caption>
            <thead>
              <tr>
                <th scope="col">{t('colName')}</th>
                <th scope="col">{t('colAddress')}</th>
                <th scope="col">{t('colClient')}</th>
                <th scope="col">{t('colContract')}</th>
                <th scope="col">{t('colTag')}</th>
                <th scope="col">{t('colShare')}</th>
                <th scope="col">{t('colStatus')}</th>
                <th scope="col">{t('colActions')}</th>
              </tr>
            </thead>
            <tbody>
              {locations.map((location) => {
                const time = monthTime.get(location.id) ?? { minutes: 0, pending: 0 }
                const target = location.target_minutes_per_month
                const contact = contacts.find((row) => row.id === location.contact_id)
                return (
                  <tr key={location.id} className={location.active ? undefined : 'is-muted'}>
                    <th scope="row">
                      {/* The name opens the building's object surface, where the five
                          numbers and the eleven links live. */}
                      <Link href={filterHref('/', { location: location.id })}>
                        {location.name}
                        <span className="visually-hidden"> {t('openPanel')}</span>
                      </Link>
                      <span className="tag-uuid">
                        {' '}
                        <code className="code-inline">{location.slug}</code>
                      </span>
                    </th>
                    <td>
                      {location.address === null ? (
                        <span className="cell-muted">{t('noAddress')}</span>
                      ) : (
                        location.address
                      )}
                    </td>
                    <td>
                      {location.client_name === null ? (
                        <span className="cell-muted">{t('noClient')}</span>
                      ) : (
                        location.client_name
                      )}
                      <span className="shift-state-note">
                        {location.contact_name === null ? t('noContact') : location.contact_name}
                      </span>
                    </td>
                    <td>
                      {/* /contracts/ left the sidebar (decision-39). This is one of its
                          permanent ways in, and it carries the building — the price shown
                          here is a MIRROR of the current period, and the history behind it
                          is what says what March was billed at. Linked in both branches:
                          „Kein Vertrag hinterlegt" is not an empty target, it is exactly
                          the screen that states what an unpriced building does to the P&L. */}
                      <span className="num">
                        <Link href={filterHref('/contracts/', { location: location.id })}>
                          {location.monthly_contract_cents === null
                            ? t('contractNone')
                            : t('contractValue', {
                                amount: format.number(location.monthly_contract_cents / 100, {
                                  style: 'currency',
                                  currency: 'EUR',
                                }),
                              })}
                          <span className="visually-hidden"> {t('contractLink')}</span>
                        </Link>
                      </span>
                      <span className="shift-state-note num">
                        {t('timeActual', { actual: formatDuration(time.minutes) })}{' '}
                        {targetSentence(time.minutes, target)}
                      </span>
                      <span className="shift-state-note">
                        {time.pending === 0 ? '' : t('timePending', { count: time.pending })}
                      </span>
                    </td>
                    <td>
                      {/* The exact string that goes on the sticker, shown in full and never
                          elided. A URI shortened for layout is a URI somebody retypes
                          wrongly onto a tag, and the fix for that costs a site visit. */}
                      <code className="code-block">{tagUri(location.id)}</code>
                      <button
                        type="button"
                        className="btn btn-quiet"
                        onClick={() =>
                          copy(
                            tagUri(location.id),
                            t('copied', { name: location.name }),
                            t('copyFailed', { name: location.name }),
                          )
                        }
                      >
                        {t('copyTag')}
                        <span className="visually-hidden">
                          {t('forLocation', { name: location.name })}
                        </span>
                      </button>
                      <p className="tag-uuid">
                        {t('uuidLabel')} <code className="code-inline">{location.id}</code>
                      </p>
                    </td>
                    <td>{shareCell(location, contact)}</td>
                    {/* Text, not a colour: the status has to survive greyscale and a screen reader. */}
                    <td>{location.active ? t('statusActive') : t('statusInactive')}</td>
                    <td className="cell-actions">
                      <button
                        type="button"
                        className="btn btn-quiet"
                        onClick={() => openEdit(location)}
                      >
                        {t('edit')}
                        <span className="visually-hidden">
                          {t('forLocation', { name: location.name })}
                        </span>
                      </button>
                      <button
                        type="button"
                        className="btn btn-quiet"
                        onClick={() =>
                          location.active ? setPendingDeactivate(location) : toggleActive(location)
                        }
                      >
                        {location.active ? t('deactivate') : t('activate')}
                        <span className="visually-hidden">
                          {t('forLocation', { name: location.name })}
                        </span>
                      </button>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </ListPanel>

      {/* ONE drawer, TWO steps — not two drawers and not a mode flag. Step 1 is everything
          needed before a tag can be tapped; step 2 is the paperwork, which can wait. */}
      <Drawer
        open={draft !== null}
        onClose={closeDrawer}
        title={draft?.id === undefined ? t('createHeading') : t('editHeading')}
        step={step === 1 ? t('stepOne') : t('stepTwo')}
        busy={busy}
        footer={
          step === 1 ? (
            <>
              <button key="cancel" type="button" className="btn btn-ghost" onClick={closeDrawer}>
                {t('cancel')}
              </button>
              {/*
                THE `key` IS THE BUG FIX, not decoration. Without distinct keys React
                reconciles these two ternary branches as the same <button> and reuses the DOM
                node, patching type="button" into type="submit". The browser resolves a
                click's activation behaviour AFTER the React handler has flushed, so one press
                of "Weiter zum Vertrag" advanced the step AND submitted the form: every new
                Objekt was saved from step 1 with no contract, by mouse, Enter and Space alike
                (REDESIGN-A11Y.md C1). Two keys = two nodes = the second one is never the node
                that was clicked. A synthetic el.click() does NOT reproduce this, which is why
                the check that covered it stayed green; demo/audit-overlays2.mjs now uses
                Input.dispatchMouseEvent.
              */}
              <button key="next" type="button" className="btn btn-primary" onClick={goToContract}>
                {t('stepNext')}
              </button>
            </>
          ) : (
            <>
              <button key="back" type="button" className="btn btn-ghost" onClick={() => setStep(1)}>
                {t('stepBack')}
              </button>
              <button
                key="save"
                type="submit"
                form={formId}
                className="btn btn-primary"
                disabled={busy}
              >
                {busy
                  ? t('submitting')
                  : draft?.id === undefined
                    ? t('submitCreate')
                    : t('submitSave')}
              </button>
            </>
          )
        }
      >
        {draft === null ? null : (
          <form id={formId} onSubmit={onSubmit} noValidate>
            {/* Kept in the DOM so the live region survives a re-render. */}
            <p className="form-error" role="alert">
              {drawerError}
            </p>

            {/* Both steps stay MOUNTED and the inactive one is `hidden`, so a value typed on
                step 1 is still there after a trip to step 2 and back, and the browser keeps
                its own undo history for each control. `hidden` removes them from the tab
                order and from the accessibility tree, so the focus trap sees one step. */}
            <div hidden={step !== 1}>
              <Field
                id={nameId}
                label={t('fieldName')}
                required
                error={fieldErrors.name === undefined ? undefined : t(fieldErrors.name)}
              >
                <input
                  type="text"
                  required
                  value={draft.name}
                  onChange={(event) => setDraft({ ...draft, name: event.target.value })}
                  maxLength={160}
                  autoComplete="off"
                  disabled={busy}
                />
              </Field>

              <Field
                id={slugId}
                label={t('fieldSlug')}
                required
                help={t('slugHint')}
                error={fieldErrors.slug === undefined ? undefined : t(fieldErrors.slug)}
              >
                <input
                  type="text"
                  required
                  value={draft.slug}
                  onChange={(event) => setDraft({ ...draft, slug: event.target.value })}
                  maxLength={64}
                  autoComplete="off"
                  spellCheck={false}
                  disabled={busy}
                />
              </Field>

              <Field id={addressId} label={t('fieldAddress')} optional help={t('addressHint')}>
                <input
                  type="text"
                  value={draft.address}
                  onChange={(event) => setDraft({ ...draft, address: event.target.value })}
                  maxLength={300}
                  autoComplete="off"
                  disabled={busy}
                />
              </Field>

              {/* The client select carries "+ Neuer Kunde …" and expands one more field IN
                  PLACE. Not a second drawer on top of this one: a focus trap inside a focus
                  trap is a bug farm, and /clients/ must never be a prerequisite for filing
                  a building. */}
              <Field id={clientId} label={t('fieldClient')} optional help={t('clientHint')}>
                <select
                  value={draft.clientChoice}
                  onChange={(event) => chooseClient(event.target.value)}
                  disabled={busy}
                >
                  <option value={NONE}>{t('clientNone')}</option>
                  {clients.map((client) => (
                    <option key={client.id} value={String(client.id)}>
                      {client.active ? client.name : t('optionInactive', { name: client.name })}
                    </option>
                  ))}
                  <option value={NEW_ROW}>{t('clientNew')}</option>
                </select>
              </Field>

              {draft.clientChoice === NEW_ROW ? (
                <Field
                  id={newClientId}
                  label={t('fieldNewClient')}
                  required
                  error={
                    fieldErrors.newClientName === undefined
                      ? undefined
                      : t(fieldErrors.newClientName)
                  }
                >
                  <input
                    type="text"
                    required
                    value={draft.newClientName}
                    onChange={(event) => setDraft({ ...draft, newClientName: event.target.value })}
                    maxLength={160}
                    autoComplete="off"
                    disabled={busy}
                  />
                </Field>
              ) : null}

              <Field
                id={contactId}
                label={t('fieldContact')}
                optional
                help={draft.clientChoice === NONE ? t('contactNeedsClientHint') : t('contactHint')}
                error={fieldErrors.contact === undefined ? undefined : t(fieldErrors.contact)}
              >
                <select
                  value={draft.contactChoice}
                  onChange={(event) => setDraft({ ...draft, contactChoice: event.target.value })}
                  disabled={busy || draft.clientChoice === NONE}
                >
                  <option value={NONE}>{t('contactNone')}</option>
                  {contactsForClient.map((contact) => (
                    <option key={contact.id} value={String(contact.id)}>
                      {contact.active ? contact.name : t('optionInactive', { name: contact.name })}
                    </option>
                  ))}
                  <option value={NEW_ROW}>{t('contactNew')}</option>
                </select>
              </Field>

              {draft.contactChoice === NEW_ROW ? (
                <>
                  <Field
                    id={newContactId}
                    label={t('fieldNewContact')}
                    required
                    error={
                      fieldErrors.newContactName === undefined
                        ? undefined
                        : t(fieldErrors.newContactName)
                    }
                  >
                    <input
                      type="text"
                      required
                      value={draft.newContactName}
                      onChange={(event) =>
                        setDraft({ ...draft, newContactName: event.target.value })
                      }
                      maxLength={160}
                      autoComplete="off"
                      disabled={busy}
                    />
                  </Field>

                  <Field
                    id={newContactEmailId}
                    label={t('fieldNewContactEmail')}
                    optional
                    error={
                      fieldErrors.newContactEmail === undefined
                        ? undefined
                        : t(fieldErrors.newContactEmail)
                    }
                  >
                    <input
                      type="email"
                      value={draft.newContactEmail}
                      onChange={(event) =>
                        setDraft({ ...draft, newContactEmail: event.target.value })
                      }
                      maxLength={320}
                      autoComplete="off"
                      disabled={busy}
                    />
                  </Field>

                  <Field
                    id={newContactPhoneId}
                    label={t('fieldNewContactPhone')}
                    optional
                    error={
                      fieldErrors.newContactPhone === undefined
                        ? undefined
                        : t(fieldErrors.newContactPhone)
                    }
                  >
                    <input
                      type="tel"
                      value={draft.newContactPhone}
                      onChange={(event) =>
                        setDraft({ ...draft, newContactPhone: event.target.value })
                      }
                      maxLength={40}
                      autoComplete="off"
                      disabled={busy}
                    />
                  </Field>
                </>
              ) : null}
            </div>

            {/* tabIndex={-1} keeps this out of the tab order and only makes it a
                programmatic focus TARGET — the step change has to land somewhere, and every
                alternative here is a control that submits the form. */}
            <div hidden={step !== 2} ref={stepTwoRef} tabIndex={-1}>
              <p className="note">{t('stepTwoNote')}</p>

              <Field
                id={monthlyId}
                label={t('fieldMonthly')}
                optional
                help={t('monthlyHint')}
                error={fieldErrors.monthly === undefined ? undefined : t(fieldErrors.monthly)}
              >
                <input
                  type="text"
                  inputMode="decimal"
                  value={draft.monthly}
                  onChange={(event) => setDraft({ ...draft, monthly: event.target.value })}
                  disabled={busy}
                />
              </Field>

              <Field
                id={targetId}
                label={t('fieldTarget')}
                optional
                help={`${t('targetHint')} ${storedTargetNote}`}
                error={
                  fieldErrors.targetHours === undefined ? undefined : t(fieldErrors.targetHours)
                }
              >
                <input
                  type="text"
                  inputMode="numeric"
                  value={draft.targetHours}
                  onChange={(event) => setDraft({ ...draft, targetHours: event.target.value })}
                  disabled={busy}
                />
              </Field>

              <div className="field field-check">
                <input
                  id={activeId}
                  type="checkbox"
                  checked={draft.active}
                  onChange={(event) => setDraft({ ...draft, active: event.target.checked })}
                  disabled={busy}
                />
                <label htmlFor={activeId}>{t('fieldActive')}</label>
              </div>
            </div>
          </form>
        )}
      </Drawer>

      {/* The side effect is the reason this is a confirmation and not a click: standing a
          building down ALSO cuts an outsider's live link to its cleaning history. */}
      <ConfirmModal
        open={pendingDeactivate !== null}
        onClose={() => setPendingDeactivate(null)}
        onConfirm={() => {
          const target = pendingDeactivate
          setPendingDeactivate(null)
          if (target !== null) void toggleActive(target)
        }}
        title={
          pendingDeactivate === null
            ? ''
            : t('deactivateConfirmTitle', { name: pendingDeactivate.name })
        }
        body={t('deactivateConfirmBody')}
        confirmLabel={t('deactivate')}
        destructive
        busy={busy}
      />
    </>
  )
}
