'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useFormatter, useTranslations } from 'next-intl'
import { type FormEvent, useCallback, useEffect, useId, useMemo, useRef, useState } from 'react'
import {
  ApiError,
  type BuildingsSnapshot,
  type Contact,
  createClientLink,
  fetchBuildingsSnapshot,
  type Location,
  revokeClientLink,
  type Shift,
  saveClient,
  saveContact,
  saveLocation,
} from '@/lib/api'
import type { ErrorKey } from '@/lib/locale'
import { centsToPlainEuros, parseEuroToCents } from '@/lib/money'
import { LOGIN_PATH } from '@/lib/nav'
import { clientPortalUrl } from '@/lib/portal'
import {
  blocksPayroll,
  durationMinutes,
  formatDuration,
  periodStart,
  shiftState,
} from '@/lib/shifts'
import { tagUri } from '@/lib/tag'

/**
 * Buildings screen — everything about one building on one screen: where it is, who pays for
 * it, what we charge, how much time we agreed to and how much we have actually spent this
 * month, the string that goes on its NFC tag, and the link its client can be given.
 *
 * The tag URI is still the load-bearing part. A tag carries `https://…/t?l=<location uuid>`
 * (decision-21): the UUID is the identity, generated by the database, and the slug is only a
 * human label. A wrong string on a sticker is discovered when a worker taps it and nothing
 * happens, and fixing it costs a site visit — so the full URI is shown verbatim and copied
 * in one click.
 *
 * The client and the point of contact can both be CREATED FROM THIS FORM. Sending the
 * director to two other screens before they can file one building is the friction that makes
 * a non-technical user stop using the panel; /clients/ exists for tidying up afterwards and
 * is never a prerequisite.
 *
 * Deactivation is soft, always: shifts reference buildings and the history has to survive.
 * One client component with `useState` + `fetch`, because this bundle is a static export
 * (decision-16) and no server component may fetch this data.
 */

/** Mirrors v.slug() in server/lib/validate.js. The server decides for real. */
const SLUG_RE = /^[a-z0-9][a-z0-9_-]*$/
/** Shape check only, mirroring v.optionalEmail(). */
const EMAIL_RE = /^[^\s@,]+@[^\s@,.]+(\.[^\s@,.]+)+$/
/** Mirrors v.optionalPhone(): digits and separators, no letters. */
const PHONE_RE = /^[0-9+()/.\s-]+$/
/**
 * Whole hours only.
 *
 * ponytail: the column stores minutes, and the form offers hours without a fraction. Every
 * target the director quoted is a round number of hours a month, and integer hours convert
 * to minutes exactly — no float multiplication anywhere near a number that later gets
 * subtracted from recorded time. Upgrade path when a 37.5 h contract appears: accept one
 * decimal place and convert tenths to 6-minute steps, still integer-only.
 */
const HOURS_RE = /^\d{1,4}$/
/** v.optionalMinutes() ceiling, 446 400 minutes, expressed in hours. */
const MAX_TARGET_HOURS = 7440

/** '' = none, 'new' = create it inline, anything else = that row's id. */
const NEW = 'new'
const NONE = ''

type Draft = {
  /** Absent = create. Present = update that row (a UUID). */
  id?: string
  name: string
  slug: string
  address: string
  active: boolean
  /** Carried through an edit untouched: the update writes every column (see LocationInput). */
  lat: number | null
  lng: number | null
  clientChoice: string
  newClientName: string
  contactChoice: string
  newContactName: string
  newContactEmail: string
  newContactPhone: string
  /** Euros as typed. Converted to integer cents at submit, never held as a float. */
  monthly: string
  /** Whole hours as typed. Converted to integer minutes at submit. */
  targetHours: string
}

const EMPTY_DRAFT: Draft = {
  name: '',
  slug: '',
  address: '',
  active: true,
  lat: null,
  lng: null,
  clientChoice: NONE,
  newClientName: '',
  contactChoice: NONE,
  newContactName: '',
  newContactEmail: '',
  newContactPhone: '',
  monthly: '',
  targetHours: '',
}

function draftOf(location: Location): Draft {
  return {
    ...EMPTY_DRAFT,
    id: location.id,
    name: location.name,
    slug: location.slug,
    address: location.address ?? '',
    active: location.active,
    lat: location.lat,
    lng: location.lng,
    clientChoice: location.client_id === null ? NONE : String(location.client_id),
    contactChoice: location.contact_id === null ? NONE : String(location.contact_id),
    monthly:
      location.monthly_contract_cents === null
        ? ''
        : centsToPlainEuros(location.monthly_contract_cents),
    // Only whole hours can be typed here, so a stored value that is not a whole hour cannot
    // be shown in this field without changing it. It is left empty and the exact stored
    // value is named in a hint next to the field instead of being silently rounded.
    targetHours:
      location.target_minutes_per_month !== null && location.target_minutes_per_month % 60 === 0
        ? String(location.target_minutes_per_month / 60)
        : '',
  }
}

/** Message keys inside the `locations` namespace, so field errors stay translatable. */
type ErrorMessage =
  | 'errorNameRequired'
  | 'errorSlugRequired'
  | 'errorSlugShape'
  | 'errorSlugTaken'
  | 'errorClientNameRequired'
  | 'errorContactNameRequired'
  | 'errorContactNeedsClient'
  | 'errorContactEmailShape'
  | 'errorContactPhoneShape'
  | 'errorMonthlyInvalid'
  | 'errorTargetInvalid'
  | 'errorRejected'

type FieldErrors = {
  name?: ErrorMessage
  slug?: ErrorMessage
  newClientName?: ErrorMessage
  contact?: ErrorMessage
  newContactName?: ErrorMessage
  newContactEmail?: ErrorMessage
  newContactPhone?: ErrorMessage
  monthly?: ErrorMessage
  targetHours?: ErrorMessage
}

/** Recorded and not-yet-counted time for one building in the current calendar month. */
type MonthTime = { minutes: number; pending: number }

/**
 * Time per building since the 1st of this month, in the browser's local time — the director
 * compares against a wall calendar, not against UTC.
 *
 * A shift that is still open, or that the 8-hour timer closed and nobody has confirmed, is
 * counted as PENDING and not as time worked (decision-10): a start-plus-8h stub is a
 * placeholder, and adding it to the hours would answer "are we overservicing" with a guess.
 */
function timeThisMonth(shifts: readonly Shift[]): Map<string, MonthTime> {
  const from = periodStart('month', new Date())
  const byLocation = new Map<string, MonthTime>()
  for (const shift of shifts) {
    if (from !== null && new Date(shift.start_time) < from) continue
    const entry = byLocation.get(shift.location_id) ?? { minutes: 0, pending: 0 }
    if (shift.end_time === null || blocksPayroll(shiftState(shift))) entry.pending += 1
    else entry.minutes += durationMinutes(shift.start_time, shift.end_time)
    byLocation.set(shift.location_id, entry)
  }
  return byLocation
}

export default function LocationsPage() {
  const t = useTranslations('locations')
  const tError = useTranslations('error')
  const format = useFormatter()
  const router = useRouter()

  const nameId = useId()
  const slugId = useId()
  const slugHintId = useId()
  const addressId = useId()
  const addressHintId = useId()
  const clientId = useId()
  const clientHintId = useId()
  const newClientId = useId()
  const contactId = useId()
  const contactHintId = useId()
  const newContactId = useId()
  const newContactEmailId = useId()
  const newContactPhoneId = useId()
  const monthlyId = useId()
  const monthlyHintId = useId()
  const targetId = useId()
  const targetHintId = useId()
  const activeId = useId()
  const errorId = useId()
  const statusId = useId()
  const formHeadingId = useId()
  const nameRef = useRef<HTMLInputElement>(null)

  // null = still loading. Empty lists = loaded and genuinely empty, the first-run state.
  const [snapshot, setSnapshot] = useState<BuildingsSnapshot | null>(null)
  const [loadError, setLoadError] = useState<ErrorKey | null>(null)
  const [draft, setDraft] = useState<Draft>(EMPTY_DRAFT)
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({})
  const [formError, setFormError] = useState<ErrorMessage | null>(null)
  const [saved, setSaved] = useState(false)
  const [busy, setBusy] = useState(false)
  /** The link just minted, shown once. Never re-readable — see `createClientLink`. */
  const [freshLink, setFreshLink] = useState<{
    url: string
    building: string
    contact: string
  } | null>(null)
  /** Result of the last copy / share action, announced in a permanent live region. */
  const [notice, setNotice] = useState<{ ok: boolean; text: string } | null>(null)

  /** A dead session must not render an empty table that looks like "no buildings yet". */
  const handleAuthLoss = useCallback(
    (cause: unknown): boolean => {
      if (cause instanceof ApiError && (cause.status === 401 || cause.status === 403)) {
        router.replace(LOGIN_PATH)
        return true
      }
      return false
    },
    [router],
  )

  const load = useCallback(
    async (signal?: AbortSignal) => {
      try {
        setSnapshot(await fetchBuildingsSnapshot(signal))
        setLoadError(null)
      } catch (cause) {
        if (cause instanceof DOMException && cause.name === 'AbortError') return
        if (handleAuthLoss(cause)) return
        setLoadError(cause instanceof ApiError ? cause.messageKey : 'server')
      }
    },
    [handleAuthLoss],
  )

  useEffect(() => {
    const controller = new AbortController()
    void load(controller.signal)
    return () => controller.abort()
  }, [load])

  const monthTime = useMemo(() => timeThisMonth(snapshot?.shifts ?? []), [snapshot])

  const locations = snapshot?.locations ?? []
  const clients = snapshot?.clients ?? []
  const contacts = snapshot?.contacts ?? []
  const grants = snapshot?.portal_grants ?? []

  /** Contacts of the chosen company only: a contact belongs to exactly one company. */
  const contactsForClient: Contact[] =
    draft.clientChoice === NONE || draft.clientChoice === NEW
      ? []
      : contacts.filter((contact) => String(contact.client_id) === draft.clientChoice)

  function editLocation(location: Location) {
    setDraft(draftOf(location))
    setFieldErrors({})
    setFormError(null)
    setSaved(false)
    nameRef.current?.focus()
  }

  function cancelEdit() {
    setDraft(EMPTY_DRAFT)
    setFieldErrors({})
    setFormError(null)
    nameRef.current?.focus()
  }

  /** Changing the company invalidates the contact choice — a stale one belongs elsewhere. */
  function chooseClient(value: string) {
    setDraft({ ...draft, clientChoice: value, contactChoice: NONE })
  }

  /** Maps a failed save onto the field it belongs to. 409 can only be the slug. */
  function reportSaveFailure(cause: unknown) {
    if (handleAuthLoss(cause)) return
    if (cause instanceof ApiError && cause.status === 409) {
      setFieldErrors({ slug: 'errorSlugTaken' })
      setFormError('errorSlugTaken')
      return
    }
    setFormError(
      cause instanceof ApiError && cause.status >= 400 && cause.status < 500
        ? 'errorRejected'
        : null,
    )
    if (cause instanceof ApiError && (cause.status === 0 || cause.status >= 500)) {
      setFieldErrors({})
      setLoadError(cause.messageKey)
    }
  }

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (busy) return

    const name = draft.name.trim()
    const slug = draft.slug.trim().toLowerCase()
    const address = draft.address.trim()
    const newClientName = draft.newClientName.trim()
    const newContactName = draft.newContactName.trim()
    const newContactEmail = draft.newContactEmail.trim()
    const newContactPhone = draft.newContactPhone.trim()
    const monthlyCents = draft.monthly.trim() === '' ? null : parseEuroToCents(draft.monthly)
    const targetHours = draft.targetHours.trim()

    // Client-side validation is UX only — server/lib/validate.js decides for real.
    const errors: FieldErrors = {}
    if (name === '') errors.name = 'errorNameRequired'
    if (slug === '') errors.slug = 'errorSlugRequired'
    else if (slug.length > 64 || !SLUG_RE.test(slug)) errors.slug = 'errorSlugShape'
    if (draft.clientChoice === NEW && newClientName === '') {
      errors.newClientName = 'errorClientNameRequired'
    }
    if (draft.contactChoice === NEW) {
      if (draft.clientChoice === NONE) errors.contact = 'errorContactNeedsClient'
      if (newContactName === '') errors.newContactName = 'errorContactNameRequired'
      if (newContactEmail !== '' && !EMAIL_RE.test(newContactEmail)) {
        errors.newContactEmail = 'errorContactEmailShape'
      }
      if (newContactPhone !== '' && !PHONE_RE.test(newContactPhone)) {
        errors.newContactPhone = 'errorContactPhoneShape'
      }
    }
    if (draft.monthly.trim() !== '' && monthlyCents === null) errors.monthly = 'errorMonthlyInvalid'
    if (
      targetHours !== '' &&
      (!HOURS_RE.test(targetHours) || Number.parseInt(targetHours, 10) > MAX_TARGET_HOURS)
    ) {
      errors.targetHours = 'errorTargetInvalid'
    }
    setFieldErrors(errors)
    setFormError(null)
    setSaved(false)
    if (Object.keys(errors).length > 0) return

    setBusy(true)
    try {
      // A company and a person can be filed on the way to saving the building. Written
      // first, because the building has to reference their ids. If the building save then
      // fails (a taken slug), the company and the person still exist and the form is
      // pointed at them, so pressing Save again cannot create a second copy.
      let clientRef = draft.clientChoice === NONE ? null : Number(draft.clientChoice)
      if (draft.clientChoice === NEW) {
        const created = await saveClient({ name: newClientName, active: true })
        clientRef = created.id
        setDraft((current) => ({
          ...current,
          clientChoice: String(created.id),
          newClientName: '',
        }))
      }

      let contactRef = draft.contactChoice === NONE ? null : Number(draft.contactChoice)
      if (draft.contactChoice === NEW && clientRef !== null) {
        const created = await saveContact({
          client_id: clientRef,
          name: newContactName,
          email: newContactEmail,
          phone: newContactPhone,
          active: true,
        })
        contactRef = created.id
        setDraft((current) => ({
          ...current,
          contactChoice: String(created.id),
          newContactName: '',
          newContactEmail: '',
          newContactPhone: '',
        }))
      }

      await saveLocation({
        ...(draft.id === undefined ? {} : { id: draft.id }),
        name,
        slug,
        address,
        lat: draft.lat,
        lng: draft.lng,
        active: draft.active,
        client_id: clientRef,
        contact_id: contactRef,
        monthly_contract_cents: monthlyCents,
        target_minutes_per_month: targetHours === '' ? null : Number.parseInt(targetHours, 10) * 60,
      })
      setDraft(EMPTY_DRAFT)
      setSaved(true)
      await load()
      // The submit button is disabled while saving, so focus would otherwise fall to
      // <body>. Put it back where the next building gets typed.
      nameRef.current?.focus()
    } catch (cause) {
      reportSaveFailure(cause)
      // A company or a person created above is already in the database; reload so the
      // selects offer them instead of tempting a second attempt at "+ New".
      await load()
    } finally {
      setBusy(false)
    }
  }

  /**
   * Soft deactivate / reactivate. The tag on the wall stays physically valid, it just stops
   * resolving — nothing is ever destroyed, because shifts point at these rows. Every column
   * is written back: the route's UPDATE sets them all, so an omitted contract field would
   * be cleared by a click on "Deactivate".
   */
  async function toggleActive(location: Location) {
    if (busy) return
    setBusy(true)
    setSaved(false)
    setFormError(null)
    try {
      await saveLocation({
        id: location.id,
        name: location.name,
        slug: location.slug,
        address: location.address ?? '',
        lat: location.lat,
        lng: location.lng,
        active: !location.active,
        client_id: location.client_id,
        contact_id: location.contact_id,
        monthly_contract_cents: location.monthly_contract_cents,
        target_minutes_per_month: location.target_minutes_per_month,
      })
      await load()
    } catch (cause) {
      reportSaveFailure(cause)
    } finally {
      setBusy(false)
    }
  }

  /**
   * Clipboard access fails on an insecure origin and can be refused by the browser. That is
   * not fatal here: the string is on screen in full, so the fallback is to say so and let
   * the admin select it by hand rather than leave them believing a copy happened.
   */
  async function copy(text: string, okText: string, failText: string) {
    try {
      await navigator.clipboard.writeText(text)
      setNotice({ ok: true, text: okText })
    } catch {
      setNotice({ ok: false, text: failText })
    }
  }

  /**
   * Mint the link for this building's contact. The URL is only complete once the browser's
   * own origin is prefixed: the server returns a path, because it has no configured public
   * origin and inventing one would be a deploy change.
   *
   * That path (`/portal/<token>`) is the JSON API route, NOT a page — `clientPortalUrl`
   * turns it into the page a client actually opens (`/reinigung/#k=<token>`, lib/portal.ts).
   * It answers null if the API ever changes that shape, and then no link is shown at all:
   * handing the director a URL that renders JSON is worse than telling them it failed.
   */
  async function shareBuilding(location: Location, contact: Contact) {
    if (busy) return
    setBusy(true)
    setNotice(null)
    setFreshLink(null)
    try {
      const path = await createClientLink(contact.id, location.id)
      const url = clientPortalUrl(window.location.origin, path)
      if (url === null) setNotice({ ok: false, text: t('shareFailed') })
      else setFreshLink({ url, building: location.name, contact: contact.name })
      await load()
    } catch (cause) {
      if (!handleAuthLoss(cause)) setNotice({ ok: false, text: t('shareFailed') })
    } finally {
      setBusy(false)
    }
  }

  async function stopSharing(tokenHash: string, location: Location) {
    if (busy) return
    setBusy(true)
    setFreshLink(null)
    try {
      await revokeClientLink(tokenHash)
      setNotice({ ok: true, text: t('shareStopped', { building: location.name }) })
      await load()
    } catch (cause) {
      if (!handleAuthLoss(cause)) setNotice({ ok: false, text: t('shareStopFailed') })
    } finally {
      setBusy(false)
    }
  }

  /**
   * "40:00 target. That is 3:20 over the target." — the whole answer to "are we
   * overservicing this building", in words, next to where the target was typed.
   */
  function targetSentence(minutes: number, target: number | null): string {
    if (target === null) return t('timeTargetNone')
    const stated = t('timeTarget', { target: formatDuration(target) })
    if (minutes > target) {
      return `${stated} ${t('timeOver', { delta: formatDuration(minutes - target) })}`
    }
    if (minutes < target) {
      return `${stated} ${t('timeUnder', { delta: formatDuration(target - minutes) })}`
    }
    return `${stated} ${t('timeExact')}`
  }

  /**
   * Why this building can or cannot be shared, and the control to do it. A grant needs an
   * active contact and an active building (the route enforces both), so the reason is
   * spelled out rather than leaving a disabled button with no explanation.
   */
  function shareCell(location: Location, contact: Contact | undefined) {
    const grant = grants.find((row) => row.location_id === location.id)
    const canShare = contact?.active === true && location.active

    if (grant !== undefined) {
      return (
        <>
          <span>
            {t('shareActive', {
              name: grant.contact_name,
              date: format.dateTime(new Date(grant.created_at), { dateStyle: 'medium' }),
            })}
          </span>
          <p className="form-actions">
            <button
              type="button"
              className="button-secondary"
              onClick={() => stopSharing(grant.token_hash, location)}
            >
              {t('shareStop')}
              <span className="visually-hidden">{t('forLocation', { name: location.name })}</span>
            </button>
            {canShare ? (
              <button
                type="button"
                className="button-secondary"
                onClick={() => shareBuilding(location, contact)}
              >
                {t('shareNew')}
                <span className="visually-hidden">{t('forLocation', { name: location.name })}</span>
              </button>
            ) : null}
          </p>
        </>
      )
    }

    if (contact === undefined) return <span className="cell-muted">{t('shareNoContact')}</span>
    if (!contact.active) {
      return <span className="cell-muted">{t('shareContactInactive', { name: contact.name })}</span>
    }
    if (!location.active) {
      return <span className="cell-muted">{t('shareInactiveBuilding')}</span>
    }
    return (
      <button
        type="button"
        className="button-secondary"
        onClick={() => shareBuilding(location, contact)}
      >
        {t('shareButton', { name: contact.name })}
        <span className="visually-hidden">{t('forLocation', { name: location.name })}</span>
      </button>
    )
  }

  const editing = draft.id !== undefined
  const formErrorText = formError === null ? '' : t(formError)
  const editedLocation =
    draft.id === undefined ? undefined : locations.find((row) => row.id === draft.id)
  /** Named rather than rounded into the hours field. See draftOf(). */
  const storedTargetNote =
    editedLocation?.target_minutes_per_month != null &&
    editedLocation.target_minutes_per_month % 60 !== 0
      ? t('targetStored', { value: formatDuration(editedLocation.target_minutes_per_month) })
      : ''
  const truncated = snapshot !== null && snapshot.shifts.length >= snapshot.shift_limit

  return (
    <>
      <h1>{t('heading')}</h1>
      <p className="lede">{t('intro')}</p>

      <section aria-labelledby={formHeadingId}>
        <h2 id={formHeadingId}>{editing ? t('editHeading') : t('createHeading')}</h2>

        <form className="worker-form" onSubmit={onSubmit} noValidate>
          {/* Permanent live regions: a text change inside an existing region is announced
              far more reliably than a node that appears and disappears. */}
          <p className="form-error" id={errorId} role="alert">
            {formErrorText}
          </p>
          <p className="form-status" id={statusId} role="status">
            {saved ? t('saved') : ''}
          </p>

          <div className="field">
            <label htmlFor={nameId}>{t('fieldName')}</label>
            <input
              id={nameId}
              ref={nameRef}
              type="text"
              value={draft.name}
              onChange={(event) => setDraft({ ...draft, name: event.target.value })}
              maxLength={160}
              autoComplete="off"
              aria-describedby={`${nameId}-error`}
              aria-invalid={fieldErrors.name !== undefined}
              disabled={busy}
            />
            <p className="field-error" id={`${nameId}-error`} role="alert">
              {fieldErrors.name === undefined ? '' : t(fieldErrors.name)}
            </p>
          </div>

          <div className="field">
            <label htmlFor={slugId}>{t('fieldSlug')}</label>
            <input
              id={slugId}
              type="text"
              value={draft.slug}
              onChange={(event) => setDraft({ ...draft, slug: event.target.value })}
              maxLength={64}
              autoComplete="off"
              spellCheck={false}
              aria-describedby={`${slugHintId} ${slugId}-error`}
              aria-invalid={fieldErrors.slug !== undefined}
              disabled={busy}
            />
            <p className="field-hint" id={slugHintId}>
              {t('slugHint')}
            </p>
            <p className="field-error" id={`${slugId}-error`} role="alert">
              {fieldErrors.slug === undefined ? '' : t(fieldErrors.slug)}
            </p>
          </div>

          <div className="field">
            <label htmlFor={addressId}>{t('fieldAddress')}</label>
            <input
              id={addressId}
              type="text"
              value={draft.address}
              onChange={(event) => setDraft({ ...draft, address: event.target.value })}
              maxLength={300}
              autoComplete="off"
              aria-describedby={addressHintId}
              disabled={busy}
            />
            <p className="field-hint" id={addressHintId}>
              {t('addressHint')}
            </p>
          </div>

          <div className="field">
            <label htmlFor={clientId}>{t('fieldClient')}</label>
            <select
              id={clientId}
              value={draft.clientChoice}
              onChange={(event) => chooseClient(event.target.value)}
              aria-describedby={clientHintId}
              disabled={busy}
            >
              <option value={NONE}>{t('clientNone')}</option>
              {clients.map((client) => (
                <option key={client.id} value={String(client.id)}>
                  {client.active ? client.name : t('optionInactive', { name: client.name })}
                </option>
              ))}
              <option value={NEW}>{t('clientNew')}</option>
            </select>
            <p className="field-hint" id={clientHintId}>
              {t('clientHint')}
            </p>
          </div>

          {draft.clientChoice === NEW ? (
            <div className="field">
              <label htmlFor={newClientId}>{t('fieldNewClient')}</label>
              <input
                id={newClientId}
                type="text"
                value={draft.newClientName}
                onChange={(event) => setDraft({ ...draft, newClientName: event.target.value })}
                maxLength={160}
                autoComplete="off"
                aria-describedby={`${newClientId}-error`}
                aria-invalid={fieldErrors.newClientName !== undefined}
                disabled={busy}
              />
              <p className="field-error" id={`${newClientId}-error`} role="alert">
                {fieldErrors.newClientName === undefined ? '' : t(fieldErrors.newClientName)}
              </p>
            </div>
          ) : null}

          <div className="field">
            <label htmlFor={contactId}>{t('fieldContact')}</label>
            <select
              id={contactId}
              value={draft.contactChoice}
              onChange={(event) => setDraft({ ...draft, contactChoice: event.target.value })}
              aria-describedby={`${contactHintId} ${contactId}-error`}
              aria-invalid={fieldErrors.contact !== undefined}
              disabled={busy || draft.clientChoice === NONE}
            >
              <option value={NONE}>{t('contactNone')}</option>
              {contactsForClient.map((contact) => (
                <option key={contact.id} value={String(contact.id)}>
                  {contact.active ? contact.name : t('optionInactive', { name: contact.name })}
                </option>
              ))}
              <option value={NEW}>{t('contactNew')}</option>
            </select>
            <p className="field-hint" id={contactHintId}>
              {draft.clientChoice === NONE ? t('contactNeedsClientHint') : t('contactHint')}
            </p>
            <p className="field-error" id={`${contactId}-error`} role="alert">
              {fieldErrors.contact === undefined ? '' : t(fieldErrors.contact)}
            </p>
          </div>

          {draft.contactChoice === NEW ? (
            <>
              <div className="field">
                <label htmlFor={newContactId}>{t('fieldNewContact')}</label>
                <input
                  id={newContactId}
                  type="text"
                  value={draft.newContactName}
                  onChange={(event) => setDraft({ ...draft, newContactName: event.target.value })}
                  maxLength={160}
                  autoComplete="off"
                  aria-describedby={`${newContactId}-error`}
                  aria-invalid={fieldErrors.newContactName !== undefined}
                  disabled={busy}
                />
                <p className="field-error" id={`${newContactId}-error`} role="alert">
                  {fieldErrors.newContactName === undefined ? '' : t(fieldErrors.newContactName)}
                </p>
              </div>

              <div className="field">
                <label htmlFor={newContactEmailId}>{t('fieldNewContactEmail')}</label>
                <input
                  id={newContactEmailId}
                  type="email"
                  value={draft.newContactEmail}
                  onChange={(event) => setDraft({ ...draft, newContactEmail: event.target.value })}
                  maxLength={320}
                  autoComplete="off"
                  aria-describedby={`${newContactEmailId}-error`}
                  aria-invalid={fieldErrors.newContactEmail !== undefined}
                  disabled={busy}
                />
                <p className="field-error" id={`${newContactEmailId}-error`} role="alert">
                  {fieldErrors.newContactEmail === undefined ? '' : t(fieldErrors.newContactEmail)}
                </p>
              </div>

              <div className="field">
                <label htmlFor={newContactPhoneId}>{t('fieldNewContactPhone')}</label>
                <input
                  id={newContactPhoneId}
                  type="tel"
                  value={draft.newContactPhone}
                  onChange={(event) => setDraft({ ...draft, newContactPhone: event.target.value })}
                  maxLength={40}
                  autoComplete="off"
                  aria-describedby={`${newContactPhoneId}-error`}
                  aria-invalid={fieldErrors.newContactPhone !== undefined}
                  disabled={busy}
                />
                <p className="field-error" id={`${newContactPhoneId}-error`} role="alert">
                  {fieldErrors.newContactPhone === undefined ? '' : t(fieldErrors.newContactPhone)}
                </p>
              </div>
            </>
          ) : null}

          <div className="field">
            <label htmlFor={monthlyId}>{t('fieldMonthly')}</label>
            <input
              id={monthlyId}
              type="text"
              inputMode="decimal"
              value={draft.monthly}
              onChange={(event) => setDraft({ ...draft, monthly: event.target.value })}
              aria-describedby={`${monthlyHintId} ${monthlyId}-error`}
              aria-invalid={fieldErrors.monthly !== undefined}
              disabled={busy}
            />
            <p className="field-hint" id={monthlyHintId}>
              {t('monthlyHint')}
            </p>
            <p className="field-error" id={`${monthlyId}-error`} role="alert">
              {fieldErrors.monthly === undefined ? '' : t(fieldErrors.monthly)}
            </p>
          </div>

          <div className="field">
            <label htmlFor={targetId}>{t('fieldTarget')}</label>
            <input
              id={targetId}
              type="text"
              inputMode="numeric"
              value={draft.targetHours}
              onChange={(event) => setDraft({ ...draft, targetHours: event.target.value })}
              aria-describedby={`${targetHintId} ${targetId}-error`}
              aria-invalid={fieldErrors.targetHours !== undefined}
              disabled={busy}
            />
            <p className="field-hint" id={targetHintId}>
              {t('targetHint')} {storedTargetNote}
            </p>
            <p className="field-error" id={`${targetId}-error`} role="alert">
              {fieldErrors.targetHours === undefined ? '' : t(fieldErrors.targetHours)}
            </p>
          </div>

          <div className="field field-check">
            <input
              id={activeId}
              type="checkbox"
              checked={draft.active}
              onChange={(event) => setDraft({ ...draft, active: event.target.checked })}
              disabled={busy}
            />
            <label htmlFor={activeId}>{t('fieldActive')}</label>
          </div>

          <div className="form-actions">
            <button type="submit" className="button-primary" disabled={busy}>
              {busy ? t('submitting') : editing ? t('submitSave') : t('submitCreate')}
            </button>
            {editing ? (
              <button type="button" className="button-secondary" onClick={cancelEdit}>
                {t('cancel')}
              </button>
            ) : null}
          </div>
        </form>
      </section>

      <section aria-labelledby="locations-list-heading">
        <h2 id="locations-list-heading">{t('listHeading')}</h2>
        <p>{t('tagExplainer')}</p>
        <p>
          <Link href="/clients/">{t('clientsLink')}</Link>
        </p>

        {loadError !== null ? (
          <p className="form-error" role="alert">
            {tError(loadError)}
          </p>
        ) : null}

        {snapshot !== null && truncated ? (
          <p className="notice">{t('truncatedNote', { limit: snapshot.shift_limit })}</p>
        ) : null}

        {/* Permanent live region for copy / share results, outside the table so that
            re-rendering a row never destroys and recreates it. */}
        <p className={notice?.ok === false ? 'form-error' : 'form-status'} role="status">
          {notice === null ? '' : notice.text}
        </p>

        {/* The one and only sighting of the link. Not a dialog: the director has to be able
            to read it, copy it, and paste it into their mail client without the panel
            trapping focus or hiding the row it belongs to. */}
        <div role="status" aria-live="polite">
          {freshLink === null ? null : (
            <div className="notice share-panel">
              <p>
                <strong>
                  {t('shareReady', { name: freshLink.contact, building: freshLink.building })}
                </strong>
              </p>
              <code className="code-block">{freshLink.url}</code>
              <p className="form-actions">
                <button
                  type="button"
                  className="button-primary"
                  onClick={() => copy(freshLink.url, t('shareCopied'), t('shareCopyFailed'))}
                >
                  {t('shareCopy')}
                </button>
              </p>
              <p>{t('shareExplain', { name: freshLink.contact })}</p>
              <p>{t('shareOnce')}</p>
            </div>
          )}
        </div>

        {snapshot === null ? (
          <p role="status">{t('loading')}</p>
        ) : locations.length === 0 ? (
          <p>{t('emptyBody')}</p>
        ) : (
          <table className="data-table" aria-busy={busy}>
            <caption className="visually-hidden">{t('tableCaption')}</caption>
            <thead>
              <tr>
                <th scope="col">{t('colName')}</th>
                <th scope="col">{t('colAddress')}</th>
                <th scope="col">{t('colClient')}</th>
                <th scope="col">{t('colContract')}</th>
                <th scope="col">{t('colTag')}</th>
                <th scope="col">{t('colShare')}</th>
                <th scope="col">{t('colStatus')}</th>
                <th scope="col">{t('colActions')}</th>
              </tr>
            </thead>
            <tbody>
              {locations.map((location) => {
                const time = monthTime.get(location.id) ?? { minutes: 0, pending: 0 }
                const target = location.target_minutes_per_month
                const contact = contacts.find((row) => row.id === location.contact_id)
                return (
                  <tr key={location.id} className={location.active ? undefined : 'row-inactive'}>
                    <th scope="row">
                      {location.name}
                      <span className="tag-uuid">
                        {' '}
                        <code className="code-inline">{location.slug}</code>
                      </span>
                    </th>
                    <td>
                      {location.address === null ? (
                        <span className="cell-muted">{t('noAddress')}</span>
                      ) : (
                        location.address
                      )}
                    </td>
                    <td>
                      {location.client_name === null ? (
                        <span className="cell-muted">{t('noClient')}</span>
                      ) : (
                        location.client_name
                      )}
                      <span className="shift-state-note">
                        {location.contact_name === null ? t('noContact') : location.contact_name}
                      </span>
                    </td>
                    <td>
                      {location.monthly_contract_cents === null
                        ? t('contractNone')
                        : t('contractValue', {
                            amount: format.number(location.monthly_contract_cents / 100, {
                              style: 'currency',
                              currency: 'EUR',
                            }),
                          })}
                      <span className="shift-state-note">
                        {t('timeActual', { actual: formatDuration(time.minutes) })}{' '}
                        {targetSentence(time.minutes, target)}
                      </span>
                      <span className="shift-state-note">
                        {time.pending === 0 ? '' : t('timePending', { count: time.pending })}
                      </span>
                    </td>
                    <td>
                      {/* The exact string that goes on the sticker, shown in full. */}
                      <code className="code-block">{tagUri(location.id)}</code>
                      <button
                        type="button"
                        className="button-secondary"
                        onClick={() =>
                          copy(
                            tagUri(location.id),
                            t('copied', { name: location.name }),
                            t('copyFailed', { name: location.name }),
                          )
                        }
                      >
                        {t('copyTag')}
                        <span className="visually-hidden">
                          {t('forLocation', { name: location.name })}
                        </span>
                      </button>
                      <p className="tag-uuid">
                        {t('uuidLabel')} <code className="code-inline">{location.id}</code>
                      </p>
                    </td>
                    <td>{shareCell(location, contact)}</td>
                    {/* Text, not a colour: the status has to survive greyscale and a screen reader. */}
                    <td>{location.active ? t('statusActive') : t('statusInactive')}</td>
                    <td className="cell-actions">
                      <button
                        type="button"
                        className="button-secondary"
                        onClick={() => editLocation(location)}
                      >
                        {t('edit')}
                        <span className="visually-hidden">
                          {t('forLocation', { name: location.name })}
                        </span>
                      </button>
                      <button
                        type="button"
                        className="button-secondary"
                        onClick={() => toggleActive(location)}
                      >
                        {location.active ? t('deactivate') : t('activate')}
                        <span className="visually-hidden">
                          {t('forLocation', { name: location.name })}
                        </span>
                      </button>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </section>
    </>
  )
}
