'use client'

import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { type FormEvent, useCallback, useEffect, useId, useRef, useState } from 'react'
import { ApiError, fetchLocations, type Location, saveLocation } from '@/lib/api'
import type { ErrorKey } from '@/lib/locale'
import { LOGIN_PATH } from '@/lib/nav'
import { tagUri } from '@/lib/tag'

/**
 * Locations screen — the buildings under contract, and the tag URI that gets written onto
 * the NFC sticker by each entrance.
 *
 * The tag URI is the point of this screen. A tag carries `https://…/t?l=<location uuid>`
 * (decision-21): the UUID is the identity, generated by the database, and the slug is only a
 * human label that never leaves the admin panel. Writing the wrong string onto a sticker is
 * only discovered when a worker taps it and nothing happens, and fixing it means going back
 * to the building — so the full URI is shown verbatim and copied in one click.
 *
 * Deactivation is soft, always: shifts reference locations and the history has to survive.
 * One client component with `useState` + `fetch`, because this bundle is a static export
 * (decision-16) and no server component may fetch this data.
 */

/** Mirrors v.slug() in server/lib/validate.js. The server decides for real. */
const SLUG_RE = /^[a-z0-9][a-z0-9_-]*$/

type Draft = {
  /** Absent = create. Present = update that row (a UUID). */
  id?: string
  name: string
  slug: string
  address: string
  active: boolean
  /** Carried through an edit untouched: the update writes every column (see LocationInput). */
  lat: number | null
  lng: number | null
}

const EMPTY_DRAFT: Draft = { name: '', slug: '', address: '', active: true, lat: null, lng: null }

function draftOf(location: Location): Draft {
  return {
    id: location.id,
    name: location.name,
    slug: location.slug,
    address: location.address ?? '',
    active: location.active,
    lat: location.lat,
    lng: location.lng,
  }
}

/** Message keys inside the `locations` namespace, so field errors stay translatable. */
type ErrorMessage =
  | 'errorNameRequired'
  | 'errorSlugRequired'
  | 'errorSlugShape'
  | 'errorSlugTaken'
  | 'errorRejected'

type FieldErrors = { name?: ErrorMessage; slug?: ErrorMessage }

export default function LocationsPage() {
  const t = useTranslations('locations')
  const tError = useTranslations('error')
  const router = useRouter()

  const nameId = useId()
  const slugId = useId()
  const slugHintId = useId()
  const addressId = useId()
  const addressHintId = useId()
  const activeId = useId()
  const errorId = useId()
  const statusId = useId()
  const formHeadingId = useId()
  const nameRef = useRef<HTMLInputElement>(null)

  // null = still loading. [] = loaded and genuinely empty, which is the first-run state.
  const [locations, setLocations] = useState<Location[] | null>(null)
  const [loadError, setLoadError] = useState<ErrorKey | null>(null)
  const [draft, setDraft] = useState<Draft>(EMPTY_DRAFT)
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({})
  const [formError, setFormError] = useState<ErrorMessage | null>(null)
  const [saved, setSaved] = useState(false)
  const [busy, setBusy] = useState(false)
  /** Result of the last copy attempt, announced in the table's live region. */
  const [copyState, setCopyState] = useState<{ ok: boolean; name: string } | null>(null)

  /** A dead session must not render an empty table that looks like "no buildings yet". */
  const handleAuthLoss = useCallback(
    (cause: unknown): boolean => {
      if (cause instanceof ApiError && (cause.status === 401 || cause.status === 403)) {
        router.replace(LOGIN_PATH)
        return true
      }
      return false
    },
    [router],
  )

  const load = useCallback(
    async (signal?: AbortSignal) => {
      try {
        setLocations(await fetchLocations(signal))
        setLoadError(null)
      } catch (cause) {
        if (cause instanceof DOMException && cause.name === 'AbortError') return
        if (handleAuthLoss(cause)) return
        setLoadError(cause instanceof ApiError ? cause.messageKey : 'server')
      }
    },
    [handleAuthLoss],
  )

  useEffect(() => {
    const controller = new AbortController()
    void load(controller.signal)
    return () => controller.abort()
  }, [load])

  function editLocation(location: Location) {
    setDraft(draftOf(location))
    setFieldErrors({})
    setFormError(null)
    setSaved(false)
    nameRef.current?.focus()
  }

  function cancelEdit() {
    setDraft(EMPTY_DRAFT)
    setFieldErrors({})
    setFormError(null)
    nameRef.current?.focus()
  }

  /** Maps a failed upsert onto the field it belongs to. 409 can only be the slug. */
  function reportSaveFailure(cause: unknown) {
    if (handleAuthLoss(cause)) return
    if (cause instanceof ApiError && cause.status === 409) {
      setFieldErrors({ slug: 'errorSlugTaken' })
      setFormError('errorSlugTaken')
      return
    }
    setFormError(
      cause instanceof ApiError && cause.status >= 400 && cause.status < 500
        ? 'errorRejected'
        : null,
    )
    if (cause instanceof ApiError && (cause.status === 0 || cause.status >= 500)) {
      setFieldErrors({})
      setLoadError(cause.messageKey)
    }
  }

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (busy) return

    const name = draft.name.trim()
    const slug = draft.slug.trim().toLowerCase()
    const address = draft.address.trim()

    // Client-side validation is UX only — server/lib/validate.js decides for real.
    const errors: FieldErrors = {}
    if (name === '') errors.name = 'errorNameRequired'
    if (slug === '') errors.slug = 'errorSlugRequired'
    else if (slug.length > 64 || !SLUG_RE.test(slug)) errors.slug = 'errorSlugShape'
    setFieldErrors(errors)
    setFormError(null)
    setSaved(false)
    if (Object.keys(errors).length > 0) return

    setBusy(true)
    try {
      await saveLocation({
        ...(draft.id === undefined ? {} : { id: draft.id }),
        name,
        slug,
        address,
        lat: draft.lat,
        lng: draft.lng,
        active: draft.active,
      })
      setDraft(EMPTY_DRAFT)
      setSaved(true)
      await load()
      // The submit button is disabled while saving, so focus would otherwise fall to
      // <body>. Put it back where the next building gets typed.
      nameRef.current?.focus()
    } catch (cause) {
      reportSaveFailure(cause)
    } finally {
      setBusy(false)
    }
  }

  /**
   * Soft deactivate / reactivate. The tag on the wall stays physically valid, it just stops
   * resolving — nothing is ever destroyed, because shifts point at these rows.
   */
  async function toggleActive(location: Location) {
    if (busy) return
    setBusy(true)
    setSaved(false)
    setFormError(null)
    try {
      await saveLocation({
        id: location.id,
        name: location.name,
        slug: location.slug,
        address: location.address ?? '',
        lat: location.lat,
        lng: location.lng,
        active: !location.active,
      })
      await load()
    } catch (cause) {
      reportSaveFailure(cause)
    } finally {
      setBusy(false)
    }
  }

  /**
   * Clipboard access fails on an insecure origin and can be refused by the browser. That is
   * not fatal here: the URI is on screen in full, so the fallback is to say so and let the
   * admin select it by hand rather than to leave them believing a copy happened.
   */
  async function copyTagUri(location: Location) {
    try {
      await navigator.clipboard.writeText(tagUri(location.id))
      setCopyState({ ok: true, name: location.name })
    } catch {
      setCopyState({ ok: false, name: location.name })
    }
  }

  const editing = draft.id !== undefined
  const formErrorText = formError === null ? '' : t(formError)
  const copyText =
    copyState === null
      ? ''
      : copyState.ok
        ? t('copied', { name: copyState.name })
        : t('copyFailed', { name: copyState.name })

  return (
    <>
      <h1>{t('heading')}</h1>
      <p className="lede">{t('intro')}</p>

      <section aria-labelledby={formHeadingId}>
        <h2 id={formHeadingId}>{editing ? t('editHeading') : t('createHeading')}</h2>

        <form className="worker-form" onSubmit={onSubmit} noValidate>
          {/* Permanent live regions: a text change inside an existing region is announced
              far more reliably than a node that appears and disappears. */}
          <p className="form-error" id={errorId} role="alert">
            {formErrorText}
          </p>
          <p className="form-status" id={statusId} role="status">
            {saved ? t('saved') : ''}
          </p>

          <div className="field">
            <label htmlFor={nameId}>{t('fieldName')}</label>
            <input
              id={nameId}
              ref={nameRef}
              type="text"
              value={draft.name}
              onChange={(event) => setDraft({ ...draft, name: event.target.value })}
              maxLength={160}
              autoComplete="off"
              aria-describedby={`${nameId}-error`}
              aria-invalid={fieldErrors.name !== undefined}
              disabled={busy}
            />
            <p className="field-error" id={`${nameId}-error`} role="alert">
              {fieldErrors.name === undefined ? '' : t(fieldErrors.name)}
            </p>
          </div>

          <div className="field">
            <label htmlFor={slugId}>{t('fieldSlug')}</label>
            <input
              id={slugId}
              type="text"
              value={draft.slug}
              onChange={(event) => setDraft({ ...draft, slug: event.target.value })}
              maxLength={64}
              autoComplete="off"
              spellCheck={false}
              aria-describedby={`${slugHintId} ${slugId}-error`}
              aria-invalid={fieldErrors.slug !== undefined}
              disabled={busy}
            />
            <p className="field-hint" id={slugHintId}>
              {t('slugHint')}
            </p>
            <p className="field-error" id={`${slugId}-error`} role="alert">
              {fieldErrors.slug === undefined ? '' : t(fieldErrors.slug)}
            </p>
          </div>

          <div className="field">
            <label htmlFor={addressId}>{t('fieldAddress')}</label>
            <input
              id={addressId}
              type="text"
              value={draft.address}
              onChange={(event) => setDraft({ ...draft, address: event.target.value })}
              maxLength={300}
              autoComplete="off"
              aria-describedby={addressHintId}
              disabled={busy}
            />
            <p className="field-hint" id={addressHintId}>
              {t('addressHint')}
            </p>
          </div>

          <div className="field field-check">
            <input
              id={activeId}
              type="checkbox"
              checked={draft.active}
              onChange={(event) => setDraft({ ...draft, active: event.target.checked })}
              disabled={busy}
            />
            <label htmlFor={activeId}>{t('fieldActive')}</label>
          </div>

          <div className="form-actions">
            <button type="submit" className="button-primary" disabled={busy}>
              {busy ? t('submitting') : editing ? t('submitSave') : t('submitCreate')}
            </button>
            {editing ? (
              <button type="button" className="button-secondary" onClick={cancelEdit}>
                {t('cancel')}
              </button>
            ) : null}
          </div>
        </form>
      </section>

      <section aria-labelledby="locations-list-heading">
        <h2 id="locations-list-heading">{t('listHeading')}</h2>
        <p>{t('tagExplainer')}</p>

        {loadError !== null ? (
          <p className="form-error" role="alert">
            {tError(loadError)}
          </p>
        ) : null}

        {/* Permanent live region for the copy result, outside the table so re-rendering a
            row never destroys and recreates it. */}
        <p className={copyState?.ok === false ? 'form-error' : 'form-status'} role="status">
          {copyText}
        </p>

        {locations === null ? (
          <p role="status">{t('loading')}</p>
        ) : locations.length === 0 ? (
          <p>{t('emptyBody')}</p>
        ) : (
          <table className="data-table" aria-busy={busy}>
            <caption className="visually-hidden">{t('tableCaption')}</caption>
            <thead>
              <tr>
                <th scope="col">{t('colName')}</th>
                <th scope="col">{t('colSlug')}</th>
                <th scope="col">{t('colAddress')}</th>
                <th scope="col">{t('colTag')}</th>
                <th scope="col">{t('colStatus')}</th>
                <th scope="col">{t('colActions')}</th>
              </tr>
            </thead>
            <tbody>
              {locations.map((location) => (
                <tr key={location.id} className={location.active ? undefined : 'row-inactive'}>
                  <th scope="row">{location.name}</th>
                  <td>
                    <code className="code-inline">{location.slug}</code>
                  </td>
                  <td>
                    {location.address === null ? (
                      <span className="cell-muted">{t('noAddress')}</span>
                    ) : (
                      location.address
                    )}
                  </td>
                  <td>
                    {/* The exact string that goes on the sticker, shown in full. */}
                    <code className="code-block">{tagUri(location.id)}</code>
                    <button
                      type="button"
                      className="button-secondary"
                      onClick={() => copyTagUri(location)}
                    >
                      {t('copyTag')}
                      <span className="visually-hidden">
                        {t('forLocation', { name: location.name })}
                      </span>
                    </button>
                    <p className="tag-uuid">
                      {t('uuidLabel')} <code className="code-inline">{location.id}</code>
                    </p>
                  </td>
                  {/* Text, not a colour: the status has to survive greyscale and a screen reader. */}
                  <td>{location.active ? t('statusActive') : t('statusInactive')}</td>
                  <td className="cell-actions">
                    <button
                      type="button"
                      className="button-secondary"
                      onClick={() => editLocation(location)}
                    >
                      {t('edit')}
                      <span className="visually-hidden">
                        {t('forLocation', { name: location.name })}
                      </span>
                    </button>
                    <button
                      type="button"
                      className="button-secondary"
                      onClick={() => toggleActive(location)}
                    >
                      {location.active ? t('deactivate') : t('activate')}
                      <span className="visually-hidden">
                        {t('forLocation', { name: location.name })}
                      </span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </>
  )
}
